// vue-router-cspt-lab/src/pages/ProductPage.vue
<script setup lang="ts">
import { useRoute } from 'vue-router'
import { ref, watchEffect, computed } from 'vue'

const route = useRoute()
const productData = ref<any>(null)
const fetchUrl = ref('')
const fetchError = ref('')

// CSPT SINK: String concatenation with multiple DECODED params
// /shop/..%2F..%2Fadmin/anything → category = "../../admin" (decoded)
// URL: /api/shop/../../admin/products/anything → /api/admin/products/anything
watchEffect(async () => {
  const url = '/api/shop/' + route.params.category + '/products/' + route.params.productId
  fetchUrl.value = url
  fetchError.value = ''
  productData.value = null
  try {
    const res = await fetch(url)
    productData.value = await res.json()
  } catch (e: any) {
    fetchError.value = e.message || 'fetch failed'
  }
})

const category = computed(() => route.params.category as string)
const productId = computed(() => route.params.productId as string)
const hasTraversal = computed(() =>
  category.value.includes('..') || category.value.includes('/') ||
  productId.value.includes('..') || productId.value.includes('/')
)
const borderColor = computed(() => hasTraversal.value ? '#f44' : '#555')
</script>

<template>
  <div :style="{ padding: '2rem', fontFamily: 'monospace', maxWidth: '700px' }">
    <h1>route.params — Multi-Param Concatenation</h1>
    <p :style="{ color: '#888' }">
      Source: <code>route.params.category</code> + <code>route.params.productId</code>.
      Both params are DECODED. String concatenation builds the fetch URL — first
      traversal-containing param breaks path boundaries.
    </p>

    <!-- SOURCE box -->
    <div :style="{
      background: '#1a1a1a',
      border: '1px solid #333',
      borderRadius: '6px',
      padding: '1rem',
      marginBottom: '1rem'
    }">
      <div :style="{ color: '#888', fontSize: '0.8rem', marginBottom: '4px' }">SOURCE</div>
      <code :style="{ color: '#f90' }">const url = '/api/shop/' + route.params.category + '/products/' + route.params.productId</code>
      <div :style="{ color: '#888', fontSize: '0.8rem', marginTop: '6px' }">
        Route: <code>/shop/:category/:productId</code> — both params independently decoded
      </div>
    </div>

    <!-- RAW VALUE box -->
    <div :style="{
      background: '#1a1a1a',
      border: `1px solid ${borderColor}`,
      borderRadius: '6px',
      padding: '1rem',
      marginBottom: '1rem'
    }">
      <div :style="{ color: '#888', fontSize: '0.8rem', marginBottom: '4px' }">RAW VALUES from route.params</div>
      <div>
        <code :style="{ color: (category.includes('..') || category.includes('/')) ? '#f44' : '#ccc' }">
          category = {{ JSON.stringify(category) }}
        </code>
        <span v-if="category.includes('..') || category.includes('/')" :style="{ color: '#f44', fontSize: '0.8rem', marginLeft: '8px' }">DECODED</span>
      </div>
      <div :style="{ marginTop: '4px' }">
        <code :style="{ color: (productId.includes('..') || productId.includes('/')) ? '#f44' : '#ccc' }">
          productId = {{ JSON.stringify(productId) }}
        </code>
        <span v-if="productId.includes('..') || productId.includes('/')" :style="{ color: '#f44', fontSize: '0.8rem', marginLeft: '8px' }">DECODED</span>
      </div>
      <div v-if="hasTraversal" :style="{ color: '#f44', fontSize: '0.8rem', marginTop: '8px' }">
        DANGEROUS: At least one param decoded to contain traversal — breaks intended path boundary
      </div>
    </div>

    <!-- FETCH URL box -->
    <div :style="{
      background: '#1a1a1a',
      border: `1px solid ${hasTraversal ? '#f44' : '#555'}`,
      borderRadius: '6px',
      padding: '1rem',
      marginBottom: '1rem'
    }">
      <div :style="{ color: '#888', fontSize: '0.8rem', marginBottom: '4px' }">FETCH URL CONSTRUCTED</div>
      <code :style="{ color: hasTraversal ? '#f44' : '#ccc', fontSize: '1rem' }">
        {{ fetchUrl || 'loading...' }}
      </code>
      <div v-if="hasTraversal" :style="{ color: '#f44', fontSize: '0.8rem', marginTop: '6px' }">
        Path traversal in concatenated URL — browser normalizes ../ segments
      </div>
    </div>

    <!-- RESULT box -->
    <div :style="{
      background: '#1a1a1a',
      border: '1px solid #555',
      borderRadius: '6px',
      padding: '1rem'
    }">
      <div :style="{ color: '#888', fontSize: '0.8rem', marginBottom: '4px' }">RESULT from fetch</div>
      <pre v-if="productData" :style="{ margin: 0, color: '#ccc' }">{{ JSON.stringify(productData, null, 2) }}</pre>
      <div v-else-if="fetchError" :style="{ color: '#f44' }">Error: {{ fetchError }} (fetch attempted — server 404 expected)</div>
      <div v-else :style="{ color: '#555' }">loading...</div>
    </div>

    <div :style="{ marginTop: '1.5rem', color: '#888', fontSize: '0.8rem' }">
      Test URLs:
      <a href="/shop/..%2F..%2Fadmin/anything" :style="{ color: '#f44', display: 'block' }">/shop/..%2F..%2Fadmin/anything</a>
      <a href="/shop/electronics/99" :style="{ color: '#4a4', display: 'block' }">/shop/electronics/99</a>
    </div>
  </div>
</template>

// react-cspt-lab/src/pages/ProductPage.tsx
import { useState, useEffect } from "react";
import { useParams } from "react-router";

// CSPT Pattern: multiple useParams() → fetch concatenation
// Risk: HIGH — both params decoded, either can carry traversal
// URL: /shop/electronics%2Fhacked/99 → category = "electronics/hacked"
export default function ProductPage() {
  const { category, productId } = useParams<{ category: string; productId: string }>();
  const [product, setProduct] = useState<unknown>(null);
  const [fetchUrl, setFetchUrl] = useState("");

  useEffect(() => {
    const url = `/api/shop/${category}/products/${productId}`;
    setFetchUrl(url);
    fetch(url)
      .then((r) => r.json())
      .catch(() => ({ error: "fetch failed (expected — no server)" }))
      .then(setProduct);
  }, [category, productId]);

  const categoryDangerous =
    (category?.includes("..") || category?.includes("/")) ?? false;
  const productDangerous =
    (productId?.includes("..") || productId?.includes("/")) ?? false;
  const isDangerous = categoryDangerous || productDangerous;

  return (
    <div style={{ padding: "2rem", fontFamily: "monospace", maxWidth: 700 }}>
      <h1>useParams() — Multiple Params</h1>
      <p style={{ color: "#888" }}>
        Source: <code>useParams()</code> reading both <code>:category</code> and{" "}
        <code>:productId</code>. React Router decodes all path params — either
        one can carry a traversal payload.
      </p>

      <div
        style={{
          background: "#1a1a1a",
          border: "1px solid #333",
          borderRadius: 6,
          padding: "1rem",
          marginBottom: "1rem",
        }}
      >
        <div style={{ color: "#888", fontSize: "0.8rem", marginBottom: 4 }}>
          SOURCE
        </div>
        <code style={{ color: "#f90" }}>
          {"const { category, productId } = useParams()"}
        </code>
        <br />
        <code style={{ color: "#f90", fontSize: "0.85rem" }}>
          {"`/api/shop/${category}/products/${productId}`"}
        </code>
      </div>

      <div
        style={{
          background: "#1a1a1a",
          border: `1px solid ${isDangerous ? "#f44" : "#4a4"}`,
          borderRadius: 6,
          padding: "1rem",
          marginBottom: "1rem",
        }}
      >
        <div style={{ color: "#888", fontSize: "0.8rem", marginBottom: 4 }}>
          RAW VALUES from useParams()
        </div>

        <div style={{ marginBottom: 8 }}>
          <code
            style={{
              color: categoryDangerous ? "#f44" : "#4a4",
              fontSize: "1rem",
            }}
          >
            category = {JSON.stringify(category)}
          </code>
          {categoryDangerous && (
            <span
              style={{
                marginLeft: 8,
                color: "#f44",
                fontSize: "0.75rem",
              }}
            >
              DANGEROUS — decoded
            </span>
          )}
        </div>

        <div>
          <code
            style={{
              color: productDangerous ? "#f44" : "#4a4",
              fontSize: "1rem",
            }}
          >
            productId = {JSON.stringify(productId)}
          </code>
          {productDangerous && (
            <span
              style={{
                marginLeft: 8,
                color: "#f44",
                fontSize: "0.75rem",
              }}
            >
              DANGEROUS — decoded
            </span>
          )}
        </div>

        <div
          style={{
            color: isDangerous ? "#f44" : "#4a4",
            fontSize: "0.8rem",
            marginTop: 8,
          }}
        >
          {isDangerous
            ? "DANGEROUS: At least one param was decoded — traversal active"
            : "No traversal — try /shop/electronics%2Fhacked/99 to test :category"}
        </div>
      </div>

      <div
        style={{
          background: "#1a1a1a",
          border: `1px solid ${isDangerous ? "#f44" : "#555"}`,
          borderRadius: 6,
          padding: "1rem",
          marginBottom: "1rem",
        }}
      >
        <div style={{ color: "#888", fontSize: "0.8rem", marginBottom: 4 }}>
          FETCH URL CONSTRUCTED
        </div>
        <code style={{ color: isDangerous ? "#f44" : "#ccc", fontSize: "1rem" }}>
          {fetchUrl || "loading..."}
        </code>
        {isDangerous && (
          <div style={{ color: "#f44", fontSize: "0.8rem", marginTop: 6 }}>
            DANGEROUS: Decoded param injected into URL — traversal is active
          </div>
        )}
      </div>

      <div
        style={{
          background: "#1a1a1a",
          border: "1px solid #555",
          borderRadius: 6,
          padding: "1rem",
        }}
      >
        <div style={{ color: "#888", fontSize: "0.8rem", marginBottom: 4 }}>
          RESULT from fetch
        </div>
        <pre style={{ margin: 0, color: "#ccc" }}>
          {JSON.stringify(product, null, 2)}
        </pre>
      </div>
    </div>
  );
}
