// sveltekit-cspt-lab/src/routes/teams/[teamId]/members/[memberId]/+page.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import { onMount } from 'svelte';

	let result = $state<unknown>(null);
	let fetchUrl = $state('');
	let mounted = $state(false);

	onMount(() => {
		mounted = true;
		const teamId = $page.params.teamId;
		const memberId = $page.params.memberId;
		const url = `/api/teams/${teamId}/members/${memberId}`;
		fetchUrl = url;
		fetch(url)
			.then((r) => r.json())
			.then((d) => (result = d))
			.catch((e) => (result = { error: String(e) }));
	});
</script>

<div style="padding: 2rem; font-family: monospace; max-width: 700px; background: #111; min-height: 100vh; color: #ccc;">
  <h1 style="color: #fff;">$page.params — Nested Route Params</h1>
  <p style="color: #888;">
    Source: <code>$page.params.teamId</code> + <code>$page.params.memberId</code>.
    SvelteKit decodes both nested params — traversal possible at either level.
  </p>

  <!-- SOURCE box -->
  <div style="background: #1a1a1a; border: 1px solid #333; border-radius: 6px; padding: 1rem; margin-bottom: 1rem;">
    <div style="color: #888; font-size: 0.8rem; margin-bottom: 4px;">SOURCE</div>
    <code style="color: #f90;">const teamId = $page.params.teamId</code><br />
    <code style="color: #f90;">const memberId = $page.params.memberId</code><br />
    <code style="color: #f90; font-size: 0.85rem;">fetch(`/api/teams/$&#123;teamId&#125;/members/$&#123;memberId&#125;`)</code>
  </div>

  <!-- RAW VALUE box -->
  {#if mounted}
  {@const teamId = $page.params.teamId}
  {@const memberId = $page.params.memberId}
  {@const teamDanger = teamId.includes('..') || (teamId.includes('/') && teamId.includes('..'))}
  {@const memberDanger = memberId.includes('..') || (memberId.includes('/') && memberId.includes('..'))}
  {@const isDangerous = teamDanger || memberDanger}
  <div style="background: #1a1a1a; border: 1px solid {isDangerous ? '#f44' : '#555'}; border-radius: 6px; padding: 1rem; margin-bottom: 1rem;">
    <div style="color: #888; font-size: 0.8rem; margin-bottom: 4px;">RAW VALUES from $page.params</div>
    <code style="color: {teamDanger ? '#f44' : '#ccc'}; display: block;">teamId = {JSON.stringify(teamId)}</code>
    <code style="color: {memberDanger ? '#f44' : '#ccc'}; display: block; margin-top: 4px;">memberId = {JSON.stringify(memberId)}</code>
    <div style="color: {isDangerous ? '#f44' : '#888'}; font-size: 0.8rem; margin-top: 8px;">
      {#if isDangerous}
        DANGEROUS: %2F decoded in nested param — path traversal active in deeply nested route
      {:else}
        Both nested params look normal — no traversal pattern detected
      {/if}
    </div>
  </div>
  {:else}
  <div style="background: #1a1a1a; border: 1px solid #333; border-radius: 6px; padding: 1rem; margin-bottom: 1rem;">
    <div style="color: #888; font-size: 0.8rem; margin-bottom: 4px;">RAW VALUES from $page.params</div>
    <code style="color: #555;">loading...</code>
  </div>
  {/if}

  <!-- FETCH URL box -->
  <div style="background: #1a1a1a; border: 1px solid {fetchUrl && fetchUrl.includes('..') ? '#f44' : fetchUrl ? '#555' : '#333'}; border-radius: 6px; padding: 1rem; margin-bottom: 1rem;">
    <div style="color: #888; font-size: 0.8rem; margin-bottom: 4px;">FETCH URL CONSTRUCTED</div>
    <code style="color: {fetchUrl && fetchUrl.includes('..') ? '#f44' : '#ccc'}; font-size: 1rem;">
      {fetchUrl || '(waiting for mount)'}
    </code>
    {#if fetchUrl && fetchUrl.includes('..')}
    <div style="color: #f44; font-size: 0.8rem; margin-top: 6px;">
      DANGEROUS: Traversal in nested route URL — even deep nesting is exploitable
    </div>
    {/if}
  </div>

  <!-- RESULT box -->
  <div style="background: #1a1a1a; border: 1px solid #555; border-radius: 6px; padding: 1rem;">
    <div style="color: #888; font-size: 0.8rem; margin-bottom: 4px;">RESULT from fetch</div>
    <pre style="margin: 0; color: #ccc;">{JSON.stringify(result, null, 2)}</pre>
  </div>

  <div style="margin-top: 1.5rem; padding: 0.75rem; background: #0a0a1a; border: 1px solid #336; border-radius: 6px;">
    <div style="color: #888; font-size: 0.75rem; margin-bottom: 4px;">TEST PAYLOADS</div>
    <a href="/teams/1%2F..%2F..%2Fadmin/members/m1" style="color: #f44; display: block;">/teams/1%2F..%2F..%2Fadmin/members/m1 (teamId injection)</a>
    <a href="/teams/t1/members/m1" style="color: #4a4; display: block;">/teams/t1/members/m1 (normal)</a>
  </div>
</div>

// solidstart-cspt-lab/src/routes/teams/[teamId]/members/[memberId].tsx
import { useParams } from "@solidjs/router";
import { createResource, Show } from "solid-js";

// CSPT Pattern: Nested dynamic params → fetch
// Risk: LOW — SolidStart preserves encoding in nested routes too
// teamId = "../../admin" (encoded as %2e%2e%2f%2e%2e%2fadmin) stays encoded
export default function MemberPage() {
  const params = useParams<{ teamId: string; memberId: string }>();

  const [member] = createResource(
    () => [params.teamId, params.memberId] as const,
    async ([teamId, memberId]) => {
      const url = `/api/teams/${teamId}/members/${memberId}`;
      console.log("[CSPT] nested fetch URL:", url);
      const res = await fetch(url);
      return res.json();
    }
  );

  const teamEncoded = () =>
    params.teamId?.includes("%2F") || params.teamId?.includes("%2f");
  const memberEncoded = () =>
    params.memberId?.includes("%2F") || params.memberId?.includes("%2f");
  const eitherEncoded = () => teamEncoded() || memberEncoded();

  const fetchUrl = () =>
    `/api/teams/${params.teamId}/members/${params.memberId}`;

  return (
    <div style={{ padding: "2rem", "font-family": "monospace", "max-width": "700px" }}>
      <h1>useParams() — Nested Dynamic Params</h1>
      <p style={{ color: "#888" }}>
        Source: <code>useParams().teamId</code> +{" "}
        <code>useParams().memberId</code>. Nested route structure{" "}
        <code>/teams/[teamId]/members/[memberId]</code> — encoding is preserved
        in both params even at deep nesting levels.
      </p>

      {/* SOURCE box */}
      <div
        style={{
          background: "#1a1a1a",
          border: "1px solid #333",
          "border-radius": "6px",
          padding: "1rem",
          "margin-bottom": "1rem",
        }}
      >
        <div style={{ color: "#888", "font-size": "0.8rem", "margin-bottom": "4px" }}>
          SOURCE
        </div>
        <code style={{ color: "#f90" }}>
          {"const params = useParams<{ teamId: string; memberId: string }>()"}
        </code>
        <br />
        <code style={{ color: "#f90", "font-size": "0.85rem" }}>
          {"`/api/teams/${params.teamId}/members/${params.memberId}`  →  fetch()"}
        </code>
      </div>

      {/* RAW VALUE box */}
      <div
        style={{
          background: "#1a1a1a",
          border: `1px solid ${eitherEncoded() ? "#4a4" : "#555"}`,
          "border-radius": "6px",
          padding: "1rem",
          "margin-bottom": "1rem",
        }}
      >
        <div style={{ color: "#888", "font-size": "0.8rem", "margin-bottom": "4px" }}>
          RAW VALUES from useParams()
        </div>
        <code style={{ color: teamEncoded() ? "#4a4" : "#ccc", display: "block", "margin-bottom": "4px" }}>
          teamId = {JSON.stringify(params.teamId)}
          {teamEncoded() && " ✓ encoded"}
        </code>
        <code style={{ color: memberEncoded() ? "#4a4" : "#ccc", display: "block" }}>
          memberId = {JSON.stringify(params.memberId)}
          {memberEncoded() && " ✓ encoded"}
        </code>
        <div
          style={{
            color: eitherEncoded() ? "#4a4" : "#888",
            "font-size": "0.8rem",
            "margin-top": "8px",
          }}
        >
          {eitherEncoded()
            ? "SAFE: %2F preserved in nested params — deep nesting does not change encoding behavior"
            : "Try /teams/1/members/42 — or encode slashes to see preservation"}
        </div>
      </div>

      {/* FETCH URL box */}
      <div
        style={{
          background: "#1a1a1a",
          border: "1px solid #4a4",
          "border-radius": "6px",
          padding: "1rem",
          "margin-bottom": "1rem",
        }}
      >
        <div style={{ color: "#888", "font-size": "0.8rem", "margin-bottom": "4px" }}>
          FETCH URL CONSTRUCTED
        </div>
        <code style={{ color: "#4a4", "font-size": "1rem" }}>
          {fetchUrl()}
        </code>
        <div style={{ color: "#4a4", "font-size": "0.8rem", "margin-top": "6px" }}>
          Nested param values preserved — %2F cannot traverse path boundaries
        </div>
      </div>

      {/* RESULT box */}
      <div
        style={{
          background: "#1a1a1a",
          border: "1px solid #555",
          "border-radius": "6px",
          padding: "1rem",
        }}
      >
        <div style={{ color: "#888", "font-size": "0.8rem", "margin-bottom": "4px" }}>
          RESULT from fetch
        </div>
        <Show when={!member.loading} fallback={<span style={{ color: "#555" }}>loading...</span>}>
          <pre style={{ margin: 0, color: "#ccc" }}>
            {JSON.stringify(member(), null, 2)}
          </pre>
        </Show>
      </div>
    </div>
  );
}
