// nuxt-cspt-lab/pages/data/[dataId].vue
<script setup>
// CSPT SINK: Server-side useFetch with route param
// During SSR, this runs on the server — param is decoded by Vue Router
// During CSR navigation, this also runs client-side — same decoded value
// Both paths result in the decoded value flowing into the fetch URL
const route = useRoute()
const fetchUrl = computed(() => `/api/data/${route.params.dataId}`)
const { data: result } = useFetch(fetchUrl)

const hasDots = computed(() => String(route.params.dataId || '').includes('..'))
const hasSlash = computed(() => String(route.params.dataId || '').includes('/'))
</script>

<template>
  <div
    :style="{
      padding: '2rem',
      fontFamily: 'monospace',
      maxWidth: '700px',
      background: '#0d0d0d',
      minHeight: '100vh',
      color: '#ccc',
    }"
  >
    <NuxtLink to="/" :style="{ color: '#888', fontSize: '0.85rem' }">← Back to index</NuxtLink>
    <h1 :style="{ color: '#fff', margin: '0.5rem 0 0.25rem' }">useRoute().params — SSR/CSR Param (Decoded Both Ways)</h1>
    <p :style="{ color: '#888', marginBottom: '1.5rem' }">
      Source: <code>useRoute().params.dataId</code>. During SSR this executes server-side;
      during client navigation it executes client-side. Both environments receive the
      decoded value from Vue Router. Try:
      <NuxtLink to="/data/..%2F..%2Finternal" :style="{ color: '#f44' }">
        /data/..%2F..%2Finternal
      </NuxtLink>
    </p>

    <!-- SOURCE box -->
    <div
      :style="{
        background: '#1a1a1a',
        border: '1px solid #333',
        borderRadius: '6px',
        padding: '1rem',
        marginBottom: '1rem',
      }"
    >
      <div :style="{ color: '#888', fontSize: '0.8rem', marginBottom: '4px' }">SOURCE</div>
      <code :style="{ color: '#f90' }">const route = useRoute()  // SSR + CSR</code>
      <br />
      <code :style="{ color: '#f90' }">route.params.dataId  →  useFetch(`/api/data/${route.params.dataId}`)</code>
      <div :style="{ color: '#888', fontSize: '0.8rem', marginTop: '6px' }">
        Note: Nuxt useFetch runs on both server (SSR) and client (CSR) — decoded both ways
      </div>
    </div>

    <!-- RAW VALUE box -->
    <div
      :style="{
        background: '#1a1a1a',
        border: `1px solid ${hasDots ? '#f44' : '#555'}`,
        borderRadius: '6px',
        padding: '1rem',
        marginBottom: '1rem',
      }"
    >
      <div :style="{ color: '#888', fontSize: '0.8rem', marginBottom: '4px' }">RAW VALUE from useRoute().params.dataId</div>
      <code :style="{ color: hasDots ? '#f44' : '#ccc', fontSize: '1.1rem' }">
        dataId = {{ JSON.stringify(route.params.dataId) }}
      </code>
      <div :style="{ color: hasDots ? '#f44' : '#888', fontSize: '0.8rem', marginTop: '8px' }">
        <template v-if="hasDots">
          DANGEROUS: %2F decoded to / — traversal dots present. Decoded by Vue Router before JavaScript saw it.
        </template>
        <template v-else>
          Normal value — try /data/..%2F..%2Finternal to test traversal
        </template>
      </div>
    </div>

    <!-- FETCH URL box -->
    <div
      :style="{
        background: '#1a1a1a',
        border: `1px solid ${hasDots ? '#f44' : '#555'}`,
        borderRadius: '6px',
        padding: '1rem',
        marginBottom: '1rem',
      }"
    >
      <div :style="{ color: '#888', fontSize: '0.8rem', marginBottom: '4px' }">FETCH URL CONSTRUCTED</div>
      <code :style="{ color: hasDots ? '#f44' : '#ccc', fontSize: '1rem' }">
        {{ fetchUrl }}
      </code>
      <div :style="{ color: hasDots ? '#f44' : '#888', fontSize: '0.8rem', marginTop: '6px' }">
        <template v-if="hasDots">
          DANGEROUS: Traversal active — server API receives path beyond intended /api/data/ scope
        </template>
        <template v-else>
          Normal fetch URL — no traversal in this request
        </template>
      </div>
    </div>

    <!-- RESULT box -->
    <div
      :style="{
        background: '#1a1a1a',
        border: '1px solid #555',
        borderRadius: '6px',
        padding: '1rem',
      }"
    >
      <div :style="{ color: '#888', fontSize: '0.8rem', marginBottom: '4px' }">RESULT from useFetch</div>
      <pre :style="{ margin: 0, color: '#ccc', whiteSpace: 'pre-wrap' }">{{ JSON.stringify(result, null, 2) }}</pre>
    </div>
  </div>
</template>

// nextjs-cspt-lab/app/data/[dataId]/page.tsx
// SERVER COMPONENT — single dynamic param
// CSPT Pattern: await params (single) → server-side fetch
// CORRECTED: Page server components get RE-ENCODED params
// URL: /data/..%2F..%2Finternal → params.dataId = "..%2F..%2Finternal" (re-encoded!)
// SSRF via indirection: re-encoded value sent to API route, which decodes it

export default async function DataPage({
  params,
}: {
  params: Promise<{ dataId: string }>;
}) {
  const { dataId } = await params;
  const fetchUrl = `http://localhost:3000/api/data/${dataId}`;

  const res = await fetch(fetchUrl, { cache: "no-store" });
  const data = await res.json().catch(() => ({ error: "Failed to parse" }));

  const hasEncodedSlash =
    dataId.includes("%2F") || dataId.includes("%2f");

  return (
    <div style={{ padding: "2rem", fontFamily: "monospace", maxWidth: 700 }}>
      <h1>await params — Single Param Server Component</h1>
      <p style={{ color: "#888" }}>
        Source: <code>await params</code> reading <code>[dataId]</code>. Page
        server components re-encode %2F. The encoded value is forwarded to the
        API route handler which decodes it (indirect SSRF path).
      </p>

      <div
        style={{
          background: "#1a1a1a",
          border: "1px solid #333",
          borderRadius: 6,
          padding: "1rem",
          marginBottom: "1rem",
        }}
      >
        <div style={{ color: "#888", fontSize: "0.8rem", marginBottom: 4 }}>
          SOURCE
        </div>
        <code style={{ color: "#f90" }}>
          {"const { dataId } = await params"}
        </code>
        <br />
        <code style={{ color: "#f90", fontSize: "0.85rem" }}>
          {"`http://localhost:3000/api/data/${dataId}`"}
        </code>
      </div>

      <div
        style={{
          background: "#1a1a1a",
          border: "1px solid #4a4",
          borderRadius: 6,
          padding: "1rem",
          marginBottom: "1rem",
        }}
      >
        <div style={{ color: "#888", fontSize: "0.8rem", marginBottom: 4 }}>
          RAW VALUE from await params
        </div>
        <code style={{ color: "#4a4", fontSize: "1.1rem" }}>
          dataId = {JSON.stringify(dataId)}
        </code>
        <div style={{ color: "#4a4", fontSize: "0.8rem", marginTop: 8 }}>
          {hasEncodedSlash
            ? "SAFE at this layer: %2F is preserved (re-encoded by Next.js page component)"
            : "No encoded slashes in this request"}
        </div>
      </div>

      <div
        style={{
          background: "#1a1a1a",
          border: "1px solid #f90",
          borderRadius: 6,
          padding: "1rem",
          marginBottom: "1rem",
        }}
      >
        <div style={{ color: "#888", fontSize: "0.8rem", marginBottom: 4 }}>
          FETCH URL CONSTRUCTED
        </div>
        <code style={{ color: "#f90", fontSize: "1rem" }}>{fetchUrl}</code>
        <div style={{ color: "#f90", fontSize: "0.8rem", marginTop: 6 }}>
          WARNING: This URL is sent to the /api/data/ route handler. That
          handler uses await params, which DECODES %2F to / — traversal can
          occur at the handler level.
        </div>
      </div>

      <div
        style={{
          background: "#1a1a1a",
          border: "1px solid #555",
          borderRadius: 6,
          padding: "1rem",
        }}
      >
        <div style={{ color: "#888", fontSize: "0.8rem", marginBottom: 4 }}>
          RESULT from fetch
        </div>
        <pre style={{ margin: 0, color: "#ccc" }}>
          {JSON.stringify(data, null, 2)}
        </pre>
      </div>
    </div>
  );
}
