// nextjs-cspt-lab/app/page.tsx
export default function HomePage() {
  return (
    <div
      style={{
        padding: "2rem",
        fontFamily: "monospace",
        maxWidth: "900px",
        margin: "0 auto",
      }}
    >
      <h1>Next.js CSPT Lab</h1>
      <p style={{ color: "#888", marginBottom: "1rem" }}>
        Client-Side Path Traversal research lab — Next.js App Router 15.5.12
      </p>

      {/* Key finding box — keep at top */}
      <div
        style={{
          padding: "1rem",
          background: "#111",
          borderRadius: 8,
          marginBottom: "2rem",
          border: "1px solid #333",
        }}
      >
        <h3 style={{ margin: "0 0 0.5rem", color: "#f90" }}>
          Key Finding: Encoding Differential
        </h3>
        <p style={{ margin: 0, color: "#ccc", lineHeight: 1.6 }}>
          <code>await params</code> in <strong>page server components</strong>{" "}
          returns <span style={{ color: "#4a4" }}>RE-ENCODED</span> values
          (%2F stays %2F).
          <br />
          <code>await params</code> in <strong>route handlers</strong> returns{" "}
          <span style={{ color: "#f44" }}>DECODED</span> values (%2F becomes
          /).
          <br />
          <code>useParams()</code> on the <strong>client</strong> returns{" "}
          <span style={{ color: "#4a4" }}>RE-ENCODED</span> values (same as
          page components).
          <br />
          <code>useSearchParams()</code> and <code>location.hash</code> on the{" "}
          <strong>client</strong> return{" "}
          <span style={{ color: "#f44" }}>DECODED</span> values (%2F becomes
          /).
          <br />
          <strong>
            Only route handlers, searchParams, and hash decode %2F out of the
            box.
          </strong>
        </p>
      </div>

      {/* CSPT DEMO — the main event */}
      <div
        style={{
          padding: "1rem",
          background: "#1a0000",
          borderRadius: 8,
          marginBottom: "2rem",
          border: "2px solid #f44",
        }}
      >
        <h2 style={{ margin: "0 0 0.5rem", color: "#f44" }}>
          CSPT Demo: Route Handler <code>await params</code>
        </h2>
        <p style={{ color: "#ccc", margin: "0 0 0.75rem", lineHeight: 1.6 }}>
          Page <code>await params</code> re-encodes, but route handler{" "}
          <code>await params</code> <strong>decodes</strong> %2F → /. The
          catch-all proxy uses <code>new URL()</code> which resolves ../ —
          SSRF to <code>/api/internal/credentials</code>.
        </p>
        <div style={{ display: "flex", gap: "1rem", flexWrap: "wrap" }}>
          <a
            href="/cspt-await-params/docs/getting-started"
            style={{
              color: "#4a4",
              padding: "0.5rem 1rem",
              border: "1px solid #4a4",
              borderRadius: 4,
              textDecoration: "none",
            }}
          >
            Normal: /docs/getting-started
          </a>
          <a
            href="/cspt-await-params/docs/getting-started/..%2F..%2F..%2Finternal%2Fcredentials"
            style={{
              color: "#f44",
              padding: "0.5rem 1rem",
              border: "1px solid #f44",
              borderRadius: 4,
              textDecoration: "none",
              fontWeight: "bold",
            }}
          >
            CSPT: /docs/getting-started/..%2F..%2F..%2Finternal%2Fcredentials
          </a>
        </div>
      </div>

      {/* DANGEROUS SOURCES */}
      <div
        style={{
          padding: "1rem",
          background: "#1a0000",
          borderRadius: 8,
          marginBottom: "2rem",
          border: "1px solid #f44",
        }}
      >
        <h2 style={{ margin: "0 0 0.75rem", color: "#f44" }}>
          DANGEROUS SOURCES (decode %2F to /)
        </h2>

        <p style={{ color: "#888", fontSize: "0.85rem", margin: "0 0 0.75rem" }}>
          These sources return a decoded value — %2F becomes / before JavaScript
          sees it. Combined with a fetch sink, path traversal is possible.
        </p>

        <table style={{ width: "100%", borderCollapse: "collapse" }}>
          <thead>
            <tr>
              <th
                style={{
                  textAlign: "left",
                  color: "#888",
                  fontWeight: "normal",
                  paddingBottom: "0.5rem",
                  borderBottom: "1px solid #333",
                  fontSize: "0.8rem",
                }}
              >
                Source
              </th>
              <th
                style={{
                  textAlign: "left",
                  color: "#888",
                  fontWeight: "normal",
                  paddingBottom: "0.5rem",
                  borderBottom: "1px solid #333",
                  fontSize: "0.8rem",
                }}
              >
                Demo
              </th>
              <th
                style={{
                  textAlign: "left",
                  color: "#888",
                  fontWeight: "normal",
                  paddingBottom: "0.5rem",
                  borderBottom: "1px solid #333",
                  fontSize: "0.8rem",
                }}
              >
                Notes
              </th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td style={{ padding: "0.5rem 0", color: "#f44" }}>
                <code>useSearchParams()</code>
              </td>
              <td style={{ padding: "0.5rem 0.5rem" }}>
                <a
                  href="/dashboard/stats?widget=..%2F..%2Fattachments%2Fmalicious"
                  style={{ color: "#f44" }}
                >
                  /dashboard/stats?widget=..%2F..%2Fattachments%2Fmalicious
                </a>
              </td>
              <td
                style={{ padding: "0.5rem 0", color: "#888", fontSize: "0.8rem" }}
              >
                CSPT + dangerouslySetInnerHTML → XSS chain
              </td>
            </tr>
            <tr>
              <td style={{ padding: "0.5rem 0", color: "#f44" }}>
                <code>location.hash</code>
              </td>
              <td style={{ padding: "0.5rem 0.5rem" }}>
                <a
                  href="/dashboard/settings#../../admin/users"
                  style={{ color: "#f44" }}
                >
                  /dashboard/settings#../../admin/users
                </a>
              </td>
              <td
                style={{ padding: "0.5rem 0", color: "#888", fontSize: "0.8rem" }}
              >
                Literal ../ in hash, flows through service layer → fetch
              </td>
            </tr>
            <tr>
              <td style={{ padding: "0.5rem 0", color: "#f44" }}>
                <code>await params</code>
                <br />
                <span style={{ fontSize: "0.75rem", color: "#888" }}>
                  (route handler)
                </span>
              </td>
              <td style={{ padding: "0.5rem 0.5rem" }}>
                <a
                  href="/route-handler-demo/proxy?path=..%2F..%2Finternal%2Fadmin"
                  style={{ color: "#f44" }}
                >
                  /route-handler-demo/proxy?path=..%2F..%2Finternal%2Fadmin
                </a>
              </td>
              <td
                style={{ padding: "0.5rem 0", color: "#888", fontSize: "0.8rem" }}
              >
                useSearchParams → fetch → /api/proxy/[...path] handler decodes
              </td>
            </tr>
            <tr>
              <td style={{ padding: "0.5rem 0", color: "#f44" }}>
                <code>await params</code>
                <br />
                <span style={{ fontSize: "0.75rem", color: "#888" }}>
                  (route handler)
                </span>
              </td>
              <td style={{ padding: "0.5rem 0.5rem" }}>
                <a
                  href="/route-handler-demo/files?path=..%2F..%2Finternal%2Fsecrets"
                  style={{ color: "#f44" }}
                >
                  /route-handler-demo/files?path=..%2F..%2Finternal%2Fsecrets
                </a>
              </td>
              <td
                style={{ padding: "0.5rem 0", color: "#888", fontSize: "0.8rem" }}
              >
                useSearchParams → fetch → /api/files/[...path] handler decodes
              </td>
            </tr>
            <tr>
              <td style={{ padding: "0.5rem 0", color: "#f44" }}>
                <code>await params</code>
                <br />
                <span style={{ fontSize: "0.75rem", color: "#888" }}>
                  (route handler)
                </span>
              </td>
              <td style={{ padding: "0.5rem 0.5rem" }}>
                <a
                  href="/route-handler-demo/users?userId=test%2Fpath"
                  style={{ color: "#f44" }}
                >
                  /route-handler-demo/users?userId=test%2Fpath
                </a>
              </td>
              <td
                style={{ padding: "0.5rem 0", color: "#888", fontSize: "0.8rem" }}
              >
                useSearchParams → fetch → /api/users/[userId] handler decodes
              </td>
            </tr>
            <tr>
              <td style={{ padding: "0.5rem 0", color: "#f44" }}>
                <code>await params</code>
                <br />
                <span style={{ fontSize: "0.75rem", color: "#888" }}>
                  (route handler)
                </span>
              </td>
              <td style={{ padding: "0.5rem 0.5rem" }}>
                <a
                  href="/route-handler-demo/data?dataId=..%2F..%2Finternal"
                  style={{ color: "#f44" }}
                >
                  /route-handler-demo/data?dataId=..%2F..%2Finternal
                </a>
              </td>
              <td
                style={{ padding: "0.5rem 0", color: "#888", fontSize: "0.8rem" }}
              >
                useSearchParams → fetch → /api/data/[dataId] handler decodes
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      {/* SAFE SOURCES */}
      <div
        style={{
          padding: "1rem",
          background: "#001a00",
          borderRadius: 8,
          marginBottom: "2rem",
          border: "1px solid #4a4",
        }}
      >
        <h2 style={{ margin: "0 0 0.75rem", color: "#4a4" }}>
          SAFE SOURCES (re-encode %2F, stays %2F)
        </h2>

        <p style={{ color: "#888", fontSize: "0.85rem", margin: "0 0 0.75rem" }}>
          These sources re-encode %2F — the value you get in JavaScript still
          contains %2F, so it cannot cross path boundaries when used in a fetch
          URL.
        </p>

        <table style={{ width: "100%", borderCollapse: "collapse" }}>
          <thead>
            <tr>
              <th
                style={{
                  textAlign: "left",
                  color: "#888",
                  fontWeight: "normal",
                  paddingBottom: "0.5rem",
                  borderBottom: "1px solid #333",
                  fontSize: "0.8rem",
                }}
              >
                Source
              </th>
              <th
                style={{
                  textAlign: "left",
                  color: "#888",
                  fontWeight: "normal",
                  paddingBottom: "0.5rem",
                  borderBottom: "1px solid #333",
                  fontSize: "0.8rem",
                }}
              >
                Demo
              </th>
              <th
                style={{
                  textAlign: "left",
                  color: "#888",
                  fontWeight: "normal",
                  paddingBottom: "0.5rem",
                  borderBottom: "1px solid #333",
                  fontSize: "0.8rem",
                }}
              >
                Notes
              </th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td style={{ padding: "0.5rem 0", color: "#4a4" }}>
                <code>useParams()</code>
              </td>
              <td style={{ padding: "0.5rem 0.5rem" }}>
                <a href="/users/test%2Fpath" style={{ color: "#4a4" }}>
                  /users/test%2Fpath
                </a>
              </td>
              <td
                style={{ padding: "0.5rem 0", color: "#888", fontSize: "0.8rem" }}
              >
                useParams → fetch — %2F stays encoded in userId
              </td>
            </tr>
            <tr>
              <td style={{ padding: "0.5rem 0", color: "#4a4" }}>
                <code>useParams()</code>
              </td>
              <td style={{ padding: "0.5rem 0.5rem" }}>
                <a
                  href="/shop/electronics%2Fhacked/99"
                  style={{ color: "#4a4" }}
                >
                  /shop/electronics%2Fhacked/99
                </a>
              </td>
              <td
                style={{ padding: "0.5rem 0", color: "#888", fontSize: "0.8rem" }}
              >
                useParams → fetch concat — %2F stays encoded in both params
              </td>
            </tr>
            <tr>
              <td style={{ padding: "0.5rem 0", color: "#4a4" }}>
                <code>useParams()</code>
              </td>
              <td style={{ padding: "0.5rem 0.5rem" }}>
                <a href="/teams/1/members/42" style={{ color: "#4a4" }}>
                  /teams/1/members/42
                </a>
              </td>
              <td
                style={{ padding: "0.5rem 0", color: "#888", fontSize: "0.8rem" }}
              >
                useParams nested — %2F stays encoded even in deeply nested routes
              </td>
            </tr>
            <tr>
              <td style={{ padding: "0.5rem 0", color: "#4a4" }}>
                <code>await params</code>
                <br />
                <span style={{ fontSize: "0.75rem", color: "#888" }}>
                  (page component)
                </span>
              </td>
              <td style={{ padding: "0.5rem 0.5rem" }}>
                <a href="/files/thepath%2fbooya" style={{ color: "#f90" }}>
                  /files/thepath%2fbooya
                </a>
              </td>
              <td
                style={{ padding: "0.5rem 0", color: "#888", fontSize: "0.8rem" }}
              >
                catch-all page — re-encoded at this layer, but forwards to
                route handler (indirect SSRF)
              </td>
            </tr>
            <tr>
              <td style={{ padding: "0.5rem 0", color: "#4a4" }}>
                <code>await params</code>
                <br />
                <span style={{ fontSize: "0.75rem", color: "#888" }}>
                  (page component)
                </span>
              </td>
              <td style={{ padding: "0.5rem 0.5rem" }}>
                <a href="/data/test%2Fpath" style={{ color: "#f90" }}>
                  /data/test%2Fpath
                </a>
              </td>
              <td
                style={{ padding: "0.5rem 0", color: "#888", fontSize: "0.8rem" }}
              >
                single param page — re-encoded, indirect SSRF via route handler
              </td>
            </tr>
            <tr>
              <td style={{ padding: "0.5rem 0", color: "#4a4" }}>
                <code>await params</code>
                <br />
                <span style={{ fontSize: "0.75rem", color: "#888" }}>
                  (page component)
                </span>
              </td>
              <td style={{ padding: "0.5rem 0.5rem" }}>
                <a href="/docs/guide%2Fintro" style={{ color: "#f90" }}>
                  /docs/guide%2Fintro
                </a>
              </td>
              <td
                style={{ padding: "0.5rem 0", color: "#888", fontSize: "0.8rem" }}
              >
                optional catch-all page — re-encoded, indirect SSRF via route
                handler
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      {/* Encoding Diagnostics */}
      <h2 style={{ color: "#ccc" }}>Encoding Diagnostics</h2>
      <ul style={{ lineHeight: "2.2" }}>
        <li>
          <a
            href="/encoding-diff/thepath%2fbooya"
            style={{ fontWeight: "bold" }}
          >
            /encoding-diff/[...path]
          </a>
          <code
            style={{
              marginLeft: 8,
              fontSize: "0.8rem",
              color: "#f90",
              fontWeight: "bold",
            }}
          >
            ENCODING DIFFERENTIAL — page vs route handler side-by-side
          </code>
        </li>
        <li>
          <a href="/encoding-test/hello%2Fworld">
            /encoding-test/[testParam]
          </a>
          <code
            style={{ marginLeft: 8, fontSize: "0.8rem", color: "#888" }}
          >
            client encoding — useParams vs usePathname vs window.location
          </code>
        </li>
        <li>
          <a href="/encoding-catchall/a%2Fb/c">
            /encoding-catchall/[...segments]
          </a>
          <code
            style={{ marginLeft: 8, fontSize: "0.8rem", color: "#888" }}
          >
            page server component catch-all encoding
          </code>
        </li>
      </ul>

      <h2 style={{ color: "#ccc" }}>Static</h2>
      <ul style={{ lineHeight: "2.2" }}>
        <li>
          <a href="/about">/about</a>
          <code
            style={{ marginLeft: 8, fontSize: "0.8rem", color: "#888" }}
          >
            static page with client fetch
          </code>
        </li>
      </ul>
    </div>
  );
}

// angular-cspt-lab/src/app/app.ts
import { Component } from '@angular/core';
import { RouterOutlet, Router } from '@angular/router';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet],
  template: `
    @if (isHome) {
      <div style="padding: 2rem; font-family: monospace; max-width: 900px; margin: 0 auto">
        <h1>Angular Router CSPT Lab</h1>
        <p style="color: #888; margin-bottom: 1rem">
          Client-Side Path Traversal research lab — Angular 21.2.1 (standalone SPA)
        </p>

        <!-- Key Finding -->
        <div style="padding: 1rem; background: #111; border-radius: 8px; margin-bottom: 2rem; border: 1px solid #333">
          <h3 style="margin: 0 0 0.5rem; color: #f90">
            Key Finding: Angular paramMap Decodes %2F to /
          </h3>
          <p style="margin: 0; color: #ccc; line-height: 1.6">
            Angular's <code>SEGMENT_RE</code> splits on literal <code>/</code> first
            (preserving <code>%2F</code> within segments), but
            <code>decode()</code> = <code>decodeURIComponent()</code> runs BEFORE
            storing in <code>paramMap</code>.
            <span style="color: #f44">paramMap.get() returns fully decoded values</span>
            — CSPT works identically to React at the HTTP layer.
            <br>
            <code>queryParamMap</code> has a
            <span style="color: #f44">LARGER</span> attack surface because query
            params are never split on <code>/</code>.
            <br>
            Angular's <code>[innerHTML]</code> is safe by default — the XSS chain
            requires <code>bypassSecurityTrustHtml()</code>.
            <br>
            <code>router.navigate()</code>
            <span style="color: #f90">double-encodes</span> % characters —
            <code>navigateByUrl()</code> is the more dangerous sink.
          </p>
        </div>

        <!-- DANGEROUS SOURCES -->
        <div style="padding: 1rem; background: #1a0000; border-radius: 8px; margin-bottom: 2rem; border: 1px solid #f44">
          <h2 style="margin: 0 0 0.75rem; color: #f44">DANGEROUS SOURCES (decode %2F to /)</h2>
          <p style="color: #888; font-size: 0.85rem; margin: 0 0 0.75rem">
            These sources return a decoded value — %2F becomes / before your TypeScript
            sees it. Combined with an HttpClient sink, path traversal is possible.
          </p>

          <table style="width: 100%; border-collapse: collapse">
            <thead>
              <tr>
                <th style="text-align: left; color: #888; font-weight: normal; padding-bottom: 0.5rem; border-bottom: 1px solid #333; font-size: 0.8rem">Source</th>
                <th style="text-align: left; color: #888; font-weight: normal; padding-bottom: 0.5rem; border-bottom: 1px solid #333; font-size: 0.8rem">Demo</th>
                <th style="text-align: left; color: #888; font-weight: normal; padding-bottom: 0.5rem; border-bottom: 1px solid #333; font-size: 0.8rem">Notes</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td style="padding: 0.5rem 0; color: #f44">
                  <code>paramMap.get()</code><br>
                  <span style="font-size: 0.75rem; color: #888">all path params</span>
                </td>
                <td style="padding: 0.5rem 0.5rem">
                  <a href="/users/..%2Fapi%2Fsecret" style="color: #f44">/users/..%2Fapi%2Fsecret</a>
                </td>
                <td style="padding: 0.5rem 0; color: #888; font-size: 0.8rem">
                  paramMap → HttpClient — %2F decoded to / before TS sees it
                </td>
              </tr>
              <tr>
                <td style="padding: 0.5rem 0; color: #f44">
                  <code>queryParamMap.get()</code><br>
                  <span style="font-size: 0.75rem; color: #888">query params (bigger surface)</span>
                </td>
                <td style="padding: 0.5rem 0.5rem">
                  <a href="/dashboard/stats?widget=..%2F..%2Fattachments%2Fmalicious" style="color: #f44">/dashboard/stats?widget=...</a>
                </td>
                <td style="padding: 0.5rem 0; color: #888; font-size: 0.8rem">
                  CRITICAL — CSPT + bypassSecurityTrustHtml → XSS chain
                </td>
              </tr>
              <tr>
                <td style="padding: 0.5rem 0; color: #f44">
                  <code>queryParamMap.get()</code><br>
                  <span style="font-size: 0.75rem; color: #888">service layer sink</span>
                </td>
                <td style="padding: 0.5rem 0.5rem">
                  <a href="/dashboard/settings?section=../../admin/users" style="color: #f44">/dashboard/settings?section=...</a>
                </td>
                <td style="padding: 0.5rem 0; color: #888; font-size: 0.8rem">
                  queryParam → ApiService.get() — service layer hides sink
                </td>
              </tr>
              <tr>
                <td style="padding: 0.5rem 0; color: #f44">
                  <code>location.hash</code>
                </td>
                <td style="padding: 0.5rem 0.5rem">
                  <a href="/dashboard/settings#../../admin/users" style="color: #f44">/dashboard/settings#../../admin/users</a>
                </td>
                <td style="padding: 0.5rem 0; color: #888; font-size: 0.8rem">
                  Literal ../ in hash, flows through service layer → HttpClient
                </td>
              </tr>
              <tr>
                <td style="padding: 0.5rem 0; color: #f44">
                  <code>queryParamMap.get()</code><br>
                  <span style="font-size: 0.75rem; color: #888">open redirect</span>
                </td>
                <td style="padding: 0.5rem 0.5rem">
                  <a href="/dashboard?redirect=..%2F..%2Fabout" style="color: #f44">/dashboard?redirect=...</a>
                </td>
                <td style="padding: 0.5rem 0; color: #888; font-size: 0.8rem">
                  queryParam → navigateByUrl() open redirect sink
                </td>
              </tr>
            </tbody>
          </table>
        </div>

        <!-- SAFE SOURCES -->
        <div style="padding: 1rem; background: #001a00; border-radius: 8px; margin-bottom: 2rem; border: 1px solid #4a4">
          <h2 style="margin: 0 0 0.75rem; color: #4a4">SAFE SOURCES (preserve %2F encoding)</h2>
          <p style="color: #888; font-size: 0.85rem; margin: 0 0 0.75rem">
            These sources preserve %2F — the value you get in TypeScript still
            contains %2F, so it cannot cross path boundaries when used in an API URL.
          </p>
          <table style="width: 100%; border-collapse: collapse">
            <thead>
              <tr>
                <th style="text-align: left; color: #888; font-weight: normal; padding-bottom: 0.5rem; border-bottom: 1px solid #333; font-size: 0.8rem">Source</th>
                <th style="text-align: left; color: #888; font-weight: normal; padding-bottom: 0.5rem; border-bottom: 1px solid #333; font-size: 0.8rem">Demo</th>
                <th style="text-align: left; color: #888; font-weight: normal; padding-bottom: 0.5rem; border-bottom: 1px solid #333; font-size: 0.8rem">Notes</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td style="padding: 0.5rem 0; color: #4a4">
                  <code>window.location.pathname</code>
                </td>
                <td style="padding: 0.5rem 0.5rem">
                  <a href="/encoding-test/test%2Fpath" style="color: #4a4">/encoding-test/test%2Fpath</a>
                </td>
                <td style="padding: 0.5rem 0; color: #888; font-size: 0.8rem">
                  Browser-native — preserves %2F, safe to use directly in API URL
                </td>
              </tr>
              <tr>
                <td style="padding: 0.5rem 0; color: #4a4">
                  <code>router.url</code>
                </td>
                <td style="padding: 0.5rem 0.5rem">
                  <a href="/encoding-test/test%2Fpath" style="color: #4a4">/encoding-test/test%2Fpath</a>
                </td>
                <td style="padding: 0.5rem 0; color: #888; font-size: 0.8rem">
                  Serialized UrlTree — partially encoded, not fully decoded
                </td>
              </tr>
            </tbody>
          </table>
        </div>

        <!-- Angular-Specific Notes -->
        <div style="padding: 1rem; background: #111; border-radius: 8px; margin-bottom: 2rem; border: 1px solid #f90">
          <h2 style="margin: 0 0 0.75rem; color: #f90">Angular-Specific Behavior</h2>
          <ul style="color: #ccc; line-height: 2; margin: 0; padding-left: 1.5rem">
            <li>
              <strong style="color: #f90">No splat/catch-all with params:</strong>
              Angular's <code>**</code> wildcard consumes all segments but does NOT
              capture sub-paths as a parameter (unlike React's <code>*</code>)
            </li>
            <li>
              <strong style="color: #f90">%2F preservation during routing:</strong>
              <code>SEGMENT_RE = /^[^\\/()?;#]+/</code> treats %2F as 3 chars (%,2,F),
              keeping the full traversal payload in ONE segment
            </li>
            <li>
              <strong style="color: #f90">Query params = bigger surface:</strong>
              Query param values match <code>/^[^&amp;#]]+/</code> — never split on <code>/</code>
            </li>
            <li>
              <strong style="color: #f90">router.navigate() double-encodes:</strong>
              <code>encodeUriSegment()</code> re-encodes <code>%</code> to <code>%25</code> —
              use <code>navigateByUrl()</code> for string injection
            </li>
            <li>
              <strong style="color: #f90">[innerHTML] is safe by default:</strong>
              Angular's sanitizer strips dangerous content — requires
              <code>bypassSecurityTrustHtml()</code> for XSS chain
            </li>
          </ul>
        </div>

        <!-- Encoding Diagnostics -->
        <h2 style="color: #ccc">Encoding Diagnostics</h2>
        <ul style="line-height: 2.2">
          <li>
            <a href="/encoding-test/hello%2Fworld" style="font-weight: bold">/encoding-test/:testParam</a>
            <code style="margin-left: 8px; font-size: 0.8rem; color: #f44; font-weight: bold">
              paramMap vs location.pathname encoding comparison
            </code>
          </li>
        </ul>

        <!-- All Routes -->
        <h2 style="color: #ccc">All Routes</h2>
        <ul style="line-height: 2.2">
          <li>
            <a href="/users/..%2Fapi%2Fsecret" style="color: #f44">/users/:userId</a>
            <code style="margin-left: 8px; font-size: 0.8rem; color: #888">
              paramMap → HttpClient (DANGEROUS)
            </code>
          </li>
          <li>
            <a href="/shop/electronics%2Fhacked/99" style="color: #f44">/shop/:category/:productId</a>
            <code style="margin-left: 8px; font-size: 0.8rem; color: #888">
              multi-param paramMap → HttpClient (DANGEROUS)
            </code>
          </li>
          <li>
            <a href="/teams/1%2F2/members/42" style="color: #f44">/teams/:teamId/members/:memberId</a>
            <code style="margin-left: 8px; font-size: 0.8rem; color: #888">
              nested params → HttpClient (DANGEROUS)
            </code>
          </li>
          <li>
            <a href="/dashboard/stats?widget=..%2F..%2Fattachments%2Fmalicious" style="color: #f44">/dashboard/stats</a>
            <code style="margin-left: 8px; font-size: 0.8rem; color: #888">
              queryParamMap → HttpClient → bypassSecurityTrustHtml (CRITICAL)
            </code>
          </li>
          <li>
            <a href="/dashboard/settings?section=../../admin/users" style="color: #f44">/dashboard/settings</a>
            <code style="margin-left: 8px; font-size: 0.8rem; color: #888">
              queryParamMap → ApiService wrapper (DANGEROUS)
            </code>
          </li>
          <li>
            <a href="/dashboard/settings#../../admin/users" style="color: #f44">/dashboard/settings#...</a>
            <code style="margin-left: 8px; font-size: 0.8rem; color: #888">
              location.hash → service layer → HttpClient (DANGEROUS)
            </code>
          </li>
          <li>
            <a href="/dashboard?redirect=..%2F..%2Fabout" style="color: #f44">/dashboard</a>
            <code style="margin-left: 8px; font-size: 0.8rem; color: #888">
              queryParamMap → navigateByUrl() open redirect (DANGEROUS)
            </code>
          </li>
          <li>
            <a href="/about">/about</a>
            <code style="margin-left: 8px; font-size: 0.8rem; color: #888">
              static page with HttpClient fetch
            </code>
          </li>
        </ul>
      </div>
    } @else {
      <router-outlet />
    }
  `,
  styles: [],
})
export class App {
  get isHome(): boolean {
    return this.router.url === '/';
  }

  constructor(private router: Router) {}
}
