// sveltekit-cspt-lab/src/routes/encoding-test/[testParam]/+page.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import { onMount } from 'svelte';

	let windowPathname = $state('');
	let windowHref = $state('');
	let mounted = $state(false);

	const param = $derived($page.params.testParam);
	const pathname = $derived($page.url.pathname);
	const pathnameEncoded = $derived(pathname.includes('%2F') || pathname.includes('%2f'));
	const paramDecoded = $derived(param.includes('/') && pathnameEncoded);

	onMount(() => {
		mounted = true;
		windowPathname = window.location.pathname;
		windowHref = window.location.href;

		console.log('[ENCODING_TEST] $page.params.testParam:', $page.params.testParam);
		console.log('[ENCODING_TEST] $page.url.pathname:', $page.url.pathname);
		console.log('[ENCODING_TEST] $page.url.searchParams.get("q"):', $page.url.searchParams.get('q'));
		console.log('[ENCODING_TEST] window.location.pathname:', window.location.pathname);
		console.log('[ENCODING_TEST] window.location.href:', window.location.href);
	});
</script>

<div style="padding: 2rem; font-family: monospace; max-width: 700px; background: #111; min-height: 100vh; color: #ccc;">
  <h1 style="color: #fff;">Encoding Differential — $page.params vs $page.url.pathname</h1>
  <p style="color: #888;">
    SvelteKit key differential: <code>$page.params</code> decodes %2F (DANGEROUS),
    while <code>$page.url.pathname</code> preserves %2F (SAFE).
    Visit with <code>/encoding-test/hello%2Fworld</code> to see the difference.
  </p>

  <!-- SOURCE box -->
  <div style="background: #1a1a1a; border: 1px solid #333; border-radius: 6px; padding: 1rem; margin-bottom: 1rem;">
    <div style="color: #888; font-size: 0.8rem; margin-bottom: 4px;">SOURCE</div>
    <code style="color: #f90;">$page.params.testParam</code><br />
    <code style="color: #f90; font-size: 0.85rem;">$page.url.pathname</code><br />
    <code style="color: #f90; font-size: 0.85rem;">window.location.pathname</code>
  </div>

  <!-- RAW VALUE comparison box -->
  <div style="background: #1a1a1a; border: 1px solid #333; border-radius: 6px; padding: 1rem; margin-bottom: 1rem;">
    <div style="color: #888; font-size: 0.8rem; margin-bottom: 8px;">ENCODING COMPARISON</div>

    <div style="margin-bottom: 8px; padding: 8px; background: #0a0a0a; border-radius: 4px; border-left: 3px solid {paramDecoded ? '#f44' : '#555'};">
      <div style="color: #888; font-size: 0.75rem;">$page.params.testParam</div>
      <code style="color: {paramDecoded ? '#f44' : '#ccc'};">{param}</code>
      {#if paramDecoded}
      <span style="color: #f44; font-size: 0.75rem; margin-left: 8px;">DECODED — %2F became /</span>
      {/if}
    </div>

    <div style="margin-bottom: 8px; padding: 8px; background: #0a0a0a; border-radius: 4px; border-left: 3px solid {pathnameEncoded ? '#4a4' : '#555'};">
      <div style="color: #888; font-size: 0.75rem;">$page.url.pathname</div>
      <code style="color: {pathnameEncoded ? '#4a4' : '#ccc'};">{pathname}</code>
      {#if pathnameEncoded}
      <span style="color: #4a4; font-size: 0.75rem; margin-left: 8px;">SAFE — %2F preserved</span>
      {/if}
    </div>

    {#if mounted}
    <div style="margin-bottom: 8px; padding: 8px; background: #0a0a0a; border-radius: 4px; border-left: 3px solid #555;">
      <div style="color: #888; font-size: 0.75rem;">window.location.pathname</div>
      <code style="color: #ccc;">{windowPathname}</code>
    </div>

    <div style="padding: 8px; background: #0a0a0a; border-radius: 4px; border-left: 3px solid #555;">
      <div style="color: #888; font-size: 0.75rem;">$page.url.searchParams.get('q')</div>
      <code style="color: #ccc;">{$page.url.searchParams.get('q') ?? '(no q param)'}</code>
    </div>
    {/if}
  </div>

  <!-- Summary box -->
  <div style="background: #1a1a1a; border: 1px solid {paramDecoded ? '#f44' : '#333'}; border-radius: 6px; padding: 1rem; margin-bottom: 1rem;">
    <div style="color: #888; font-size: 0.8rem; margin-bottom: 4px;">ENCODING ANALYSIS</div>
    {#if paramDecoded}
    <div style="color: #f44;">
      DIFFERENTIAL CONFIRMED: $page.params decoded %2F to / — DANGEROUS for fetch construction<br />
      $page.url.pathname preserved %2F — SAFE for fetch construction
    </div>
    {:else if pathnameEncoded}
    <div style="color: #4a4;">
      $page.url.pathname preserves %2F — this is the safe source
    </div>
    {:else}
    <div style="color: #888;">
      Visit /encoding-test/hello%2Fworld to see the encoding differential
    </div>
    {/if}
  </div>

  <!-- Full table -->
  <div style="background: #1a1a1a; border: 1px solid #555; border-radius: 6px; padding: 1rem;">
    <div style="color: #888; font-size: 0.8rem; margin-bottom: 8px;">ALL SOURCES</div>
    <table style="width: 100%; border-collapse: collapse;">
      <thead>
        <tr>
          <th style="text-align: left; color: #888; font-weight: normal; font-size: 0.75rem; padding-bottom: 4px; border-bottom: 1px solid #333;">Source</th>
          <th style="text-align: left; color: #888; font-weight: normal; font-size: 0.75rem; padding-bottom: 4px; border-bottom: 1px solid #333;">Value</th>
          <th style="text-align: left; color: #888; font-weight: normal; font-size: 0.75rem; padding-bottom: 4px; border-bottom: 1px solid #333;">Safe?</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td style="padding: 4px 0; font-size: 0.85rem;">$page.params.testParam</td>
          <td style="padding: 4px 4px;"><code style="color: {paramDecoded ? '#f44' : '#ccc'};">{param}</code></td>
          <td style="padding: 4px 0; color: {paramDecoded ? '#f44' : '#888'};">{paramDecoded ? 'DANGEROUS' : 'unknown'}</td>
        </tr>
        <tr>
          <td style="padding: 4px 0; font-size: 0.85rem;">$page.url.pathname</td>
          <td style="padding: 4px 4px;"><code style="color: {pathnameEncoded ? '#4a4' : '#ccc'};">{pathname}</code></td>
          <td style="padding: 4px 0; color: {pathnameEncoded ? '#4a4' : '#888'};">{pathnameEncoded ? 'SAFE' : 'n/a'}</td>
        </tr>
        {#if mounted}
        <tr>
          <td style="padding: 4px 0; font-size: 0.85rem;">window.location.pathname</td>
          <td style="padding: 4px 4px;"><code>{windowPathname}</code></td>
          <td style="padding: 4px 0; color: #888;">-</td>
        </tr>
        <tr>
          <td style="padding: 4px 0; font-size: 0.85rem;">window.location.href</td>
          <td style="padding: 4px 4px;"><code style="font-size: 0.75rem;">{windowHref}</code></td>
          <td style="padding: 4px 0; color: #888;">-</td>
        </tr>
        {/if}
      </tbody>
    </table>
  </div>

  <div style="margin-top: 1.5rem; padding: 0.75rem; background: #0a0a1a; border: 1px solid #336; border-radius: 6px;">
    <div style="color: #888; font-size: 0.75rem; margin-bottom: 4px;">TEST PAYLOADS</div>
    <a href="/encoding-test/hello%2Fworld" style="color: #f44; display: block;">/encoding-test/hello%2Fworld (see differential)</a>
    <a href="/encoding-test/normal" style="color: #4a4; display: block;">/encoding-test/normal (no encoding)</a>
    <a href="/encoding-test/test%2Fparam?q=query%2Fval" style="color: #f90; display: block;">/encoding-test/test%2Fparam?q=query%2Fval (both sources)</a>
  </div>
</div>

// nuxt-cspt-lab/pages/encoding-test/[testParam].vue
<script setup>
// ENCODING DIAGNOSTIC: Compare decoded vs encoded representations
// Key finding: route.params.testParam = DECODED (DANGEROUS)
//              route.path = ENCODED (preserves %2F) (SAFE)
//              route.fullPath = ENCODED (preserves %2F) (SAFE)
// This is different from Next.js where useParams() re-encodes!
const route = useRoute()

const results = computed(() => ({
  'useRoute().params.testParam': route.params.testParam,
  'useRoute().path': route.path,
  'useRoute().fullPath': route.fullPath,
  'useRoute().query.q': route.query.q ?? null,
}))

const windowResults = ref({})

onMounted(() => {
  windowResults.value = {
    'window.location.pathname': window.location.pathname,
    'window.location.href': window.location.href,
    'window.location.search': window.location.search,
    'window.location.hash': window.location.hash,
  }
  console.log('[ENCODING_TEST] route.params.testParam:', route.params.testParam)
  console.log('[ENCODING_TEST] route.path:', route.path)
  console.log('[ENCODING_TEST] route.fullPath:', route.fullPath)
  console.log('[ENCODING_TEST] window.location.pathname:', window.location.pathname)
})

const paramHasSlash = computed(() => String(route.params.testParam || '').includes('/'))
const pathHasEncoded = computed(() => String(route.path || '').includes('%2F') || String(route.path || '').includes('%2f'))
</script>

<template>
  <div
    :style="{
      padding: '2rem',
      fontFamily: 'monospace',
      maxWidth: '800px',
      background: '#0d0d0d',
      minHeight: '100vh',
      color: '#ccc',
    }"
  >
    <NuxtLink to="/" :style="{ color: '#888', fontSize: '0.85rem' }">← Back to index</NuxtLink>
    <h1 :style="{ color: '#fff', margin: '0.5rem 0 0.25rem' }">Encoding Diagnostic — Nuxt 3 / Vue Router</h1>
    <p :style="{ color: '#888', marginBottom: '0.5rem' }">
      Try:
      <NuxtLink to="/encoding-test/..%2Fapi%2Fadmin" :style="{ color: '#f44' }">
        /encoding-test/..%2Fapi%2Fadmin
      </NuxtLink>
      and
      <NuxtLink to="/encoding-test/hello%2Fworld" :style="{ color: '#f44' }">
        /encoding-test/hello%2Fworld
      </NuxtLink>
    </p>
    <p :style="{ color: '#888', fontSize: '0.85rem', marginBottom: '1.5rem' }">
      Key difference from Next.js: <code>useRoute().params</code> returns
      <span :style="{ color: '#f44' }">DECODED</span> values (not re-encoded like Next.js <code>useParams()</code>).
      Only <code>route.path</code> and <code>route.fullPath</code> are safe.
    </p>

    <!-- Vue Router sources -->
    <div
      :style="{
        background: '#1a1a1a',
        border: '1px solid #333',
        borderRadius: '6px',
        padding: '1rem',
        marginBottom: '1rem',
      }"
    >
      <div :style="{ color: '#888', fontSize: '0.8rem', marginBottom: '8px' }">NUXT / VUE ROUTER SOURCES</div>
      <table :style="{ width: '100%', borderCollapse: 'collapse' }">
        <tbody>
          <tr>
            <td :style="{ padding: '0.4rem 0', color: '#888', width: '40%', fontSize: '0.9rem' }">
              <code>useRoute().params.testParam</code>
            </td>
            <td :style="{ padding: '0.4rem 0', color: paramHasSlash ? '#f44' : '#ccc' }">
              <code>{{ JSON.stringify(results['useRoute().params.testParam']) }}</code>
            </td>
            <td :style="{ padding: '0.4rem 0.5rem', fontSize: '0.75rem', color: paramHasSlash ? '#f44' : '#888' }">
              {{ paramHasSlash ? 'DECODED — / present (DANGEROUS)' : 'No slash — test with %2F payload' }}
            </td>
          </tr>
          <tr>
            <td :style="{ padding: '0.4rem 0', color: '#888', fontSize: '0.9rem' }">
              <code>useRoute().path</code>
            </td>
            <td :style="{ padding: '0.4rem 0', color: '#4a4' }">
              <code>{{ JSON.stringify(results['useRoute().path']) }}</code>
            </td>
            <td :style="{ padding: '0.4rem 0.5rem', fontSize: '0.75rem', color: '#4a4' }">
              ENCODED — %2F preserved (SAFE)
            </td>
          </tr>
          <tr>
            <td :style="{ padding: '0.4rem 0', color: '#888', fontSize: '0.9rem' }">
              <code>useRoute().fullPath</code>
            </td>
            <td :style="{ padding: '0.4rem 0', color: '#4a4' }">
              <code>{{ JSON.stringify(results['useRoute().fullPath']) }}</code>
            </td>
            <td :style="{ padding: '0.4rem 0.5rem', fontSize: '0.75rem', color: '#4a4' }">
              ENCODED — %2F preserved (SAFE)
            </td>
          </tr>
          <tr>
            <td :style="{ padding: '0.4rem 0', color: '#888', fontSize: '0.9rem' }">
              <code>useRoute().query.q</code>
            </td>
            <td :style="{ padding: '0.4rem 0', color: '#f44' }">
              <code>{{ JSON.stringify(results['useRoute().query.q']) }}</code>
            </td>
            <td :style="{ padding: '0.4rem 0.5rem', fontSize: '0.75rem', color: '#f44' }">
              DECODED (DANGEROUS) — add ?q=test%2Fval to verify
            </td>
          </tr>
        </tbody>
      </table>
    </div>

    <!-- window.location sources -->
    <div
      :style="{
        background: '#1a1a1a',
        border: '1px solid #333',
        borderRadius: '6px',
        padding: '1rem',
        marginBottom: '1rem',
      }"
    >
      <div :style="{ color: '#888', fontSize: '0.8rem', marginBottom: '8px' }">WINDOW.LOCATION SOURCES (client-only)</div>
      <table :style="{ width: '100%', borderCollapse: 'collapse' }">
        <tbody>
          <tr v-for="(val, key) in windowResults" :key="key">
            <td :style="{ padding: '0.4rem 0', color: '#888', width: '40%', fontSize: '0.9rem' }">
              <code>{{ key }}</code>
            </td>
            <td :style="{ padding: '0.4rem 0', color: '#ccc' }">
              <code>{{ JSON.stringify(val) }}</code>
            </td>
          </tr>
          <tr v-if="Object.keys(windowResults).length === 0">
            <td colspan="2" :style="{ color: '#555', padding: '0.4rem 0' }">Loading (client-only)...</td>
          </tr>
        </tbody>
      </table>
    </div>

    <!-- Summary box -->
    <div
      :style="{
        background: '#111',
        border: '1px solid #333',
        borderRadius: '6px',
        padding: '1rem',
      }"
    >
      <div :style="{ color: '#f90', fontWeight: 'bold', marginBottom: '6px' }">Nuxt 3 vs Next.js Encoding Comparison</div>
      <table :style="{ width: '100%', borderCollapse: 'collapse', fontSize: '0.85rem' }">
        <thead>
          <tr>
            <th :style="{ textAlign: 'left', color: '#888', paddingBottom: '4px', fontWeight: 'normal' }">Source</th>
            <th :style="{ textAlign: 'left', color: '#888', paddingBottom: '4px', fontWeight: 'normal' }">Nuxt 3</th>
            <th :style="{ textAlign: 'left', color: '#888', paddingBottom: '4px', fontWeight: 'normal' }">Next.js</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td :style="{ padding: '3px 0', color: '#ccc' }"><code>route params</code></td>
            <td :style="{ padding: '3px 0', color: '#f44' }">DECODED (dangerous)</td>
            <td :style="{ padding: '3px 0', color: '#4a4' }">RE-ENCODED (safe)</td>
          </tr>
          <tr>
            <td :style="{ padding: '3px 0', color: '#ccc' }"><code>route path</code></td>
            <td :style="{ padding: '3px 0', color: '#4a4' }">ENCODED (safe)</td>
            <td :style="{ padding: '3px 0', color: '#4a4' }">ENCODED (safe)</td>
          </tr>
          <tr>
            <td :style="{ padding: '3px 0', color: '#ccc' }"><code>query params</code></td>
            <td :style="{ padding: '3px 0', color: '#f44' }">DECODED (dangerous)</td>
            <td :style="{ padding: '3px 0', color: '#f44' }">DECODED (dangerous)</td>
          </tr>
          <tr>
            <td :style="{ padding: '3px 0', color: '#ccc' }"><code>server route params</code></td>
            <td :style="{ padding: '3px 0', color: '#f44' }">DECODED via H3 (SSRF)</td>
            <td :style="{ padding: '3px 0', color: '#f44' }">DECODED via route handler</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>
