// sveltekit-cspt-lab/src/routes/shop/[category]/[productId]/+page.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import { onMount } from 'svelte';

	let result = $state<unknown>(null);
	let fetchUrl = $state('');
	let mounted = $state(false);

	onMount(() => {
		mounted = true;
		const category = $page.params.category;
		const productId = $page.params.productId;
		const url = `/api/shop/${category}/products/${productId}`;
		fetchUrl = url;
		fetch(url)
			.then((r) => r.json())
			.then((d) => (result = d))
			.catch((e) => (result = { error: String(e) }));
	});
</script>

<div style="padding: 2rem; font-family: monospace; max-width: 700px; background: #111; min-height: 100vh; color: #ccc;">
  <h1 style="color: #fff;">$page.params — Multi-Param Concat</h1>
  <p style="color: #888;">
    Source: <code>$page.params.category</code> + <code>$page.params.productId</code>.
    SvelteKit decodes both params — either can contain decoded %2F to inject path traversal.
  </p>

  <!-- SOURCE box -->
  <div style="background: #1a1a1a; border: 1px solid #333; border-radius: 6px; padding: 1rem; margin-bottom: 1rem;">
    <div style="color: #888; font-size: 0.8rem; margin-bottom: 4px;">SOURCE</div>
    <code style="color: #f90;">const category = $page.params.category</code><br />
    <code style="color: #f90;">const productId = $page.params.productId</code><br />
    <code style="color: #f90; font-size: 0.85rem;">fetch(`/api/shop/$&#123;category&#125;/products/$&#123;productId&#125;`)</code>
  </div>

  <!-- RAW VALUE box -->
  {#if mounted}
  {@const category = $page.params.category}
  {@const productId = $page.params.productId}
  {@const catDanger = category.includes('..') || (category.includes('/') && !category.startsWith('/'))}
  {@const pidDanger = productId.includes('..') || (productId.includes('/') && !productId.startsWith('/'))}
  {@const isDangerous = catDanger || pidDanger}
  <div style="background: #1a1a1a; border: 1px solid {isDangerous ? '#f44' : '#555'}; border-radius: 6px; padding: 1rem; margin-bottom: 1rem;">
    <div style="color: #888; font-size: 0.8rem; margin-bottom: 4px;">RAW VALUES from $page.params</div>
    <code style="color: {catDanger ? '#f44' : '#ccc'}; display: block;">category = {JSON.stringify(category)}</code>
    <code style="color: {pidDanger ? '#f44' : '#ccc'}; display: block; margin-top: 4px;">productId = {JSON.stringify(productId)}</code>
    <div style="color: {isDangerous ? '#f44' : '#888'}; font-size: 0.8rem; margin-top: 8px;">
      {#if isDangerous}
        DANGEROUS: %2F decoded in {catDanger ? 'category' : 'productId'} — path injection active
      {:else}
        Both params look normal — no traversal pattern detected
      {/if}
    </div>
  </div>
  {:else}
  <div style="background: #1a1a1a; border: 1px solid #333; border-radius: 6px; padding: 1rem; margin-bottom: 1rem;">
    <div style="color: #888; font-size: 0.8rem; margin-bottom: 4px;">RAW VALUES from $page.params</div>
    <code style="color: #555;">loading...</code>
  </div>
  {/if}

  <!-- FETCH URL box -->
  <div style="background: #1a1a1a; border: 1px solid {fetchUrl && fetchUrl.includes('..') ? '#f44' : fetchUrl ? '#555' : '#333'}; border-radius: 6px; padding: 1rem; margin-bottom: 1rem;">
    <div style="color: #888; font-size: 0.8rem; margin-bottom: 4px;">FETCH URL CONSTRUCTED</div>
    <code style="color: {fetchUrl && fetchUrl.includes('..') ? '#f44' : '#ccc'}; font-size: 1rem;">
      {fetchUrl || '(waiting for mount)'}
    </code>
    {#if fetchUrl && fetchUrl.includes('..')}
    <div style="color: #f44; font-size: 0.8rem; margin-top: 6px;">
      DANGEROUS: Traversal segments in URL from decoded params
    </div>
    {/if}
  </div>

  <!-- RESULT box -->
  <div style="background: #1a1a1a; border: 1px solid #555; border-radius: 6px; padding: 1rem;">
    <div style="color: #888; font-size: 0.8rem; margin-bottom: 4px;">RESULT from fetch</div>
    <pre style="margin: 0; color: #ccc;">{JSON.stringify(result, null, 2)}</pre>
  </div>

  <div style="margin-top: 1.5rem; padding: 0.75rem; background: #0a0a1a; border: 1px solid #336; border-radius: 6px;">
    <div style="color: #888; font-size: 0.75rem; margin-bottom: 4px;">TEST PAYLOADS</div>
    <a href="/shop/electronics%2Fhacked/99" style="color: #f44; display: block;">/shop/electronics%2Fhacked/99 (category injection)</a>
    <a href="/shop/electronics/456" style="color: #4a4; display: block;">/shop/electronics/456 (normal)</a>
  </div>
</div>

// nuxt-cspt-lab/pages/shop/[category]/[productId].vue
<script setup>
// CSPT SINK: Multiple params flow into $fetch URL via useAsyncData
// Both category and productId are decoded by Vue Router
// Concatenated path construction amplifies traversal surface
const route = useRoute()

const fetchUrl = computed(() =>
  `/api/shop/${route.params.category}/products/${route.params.productId}`
)

const { data: product } = useAsyncData('product', () =>
  $fetch(fetchUrl.value)
, { watch: [fetchUrl] })

const categoryDots = computed(() => String(route.params.category || '').includes('..'))
const productDots = computed(() => String(route.params.productId || '').includes('..'))
const hasDots = computed(() => categoryDots.value || productDots.value)
</script>

<template>
  <div
    :style="{
      padding: '2rem',
      fontFamily: 'monospace',
      maxWidth: '700px',
      background: '#0d0d0d',
      minHeight: '100vh',
      color: '#ccc',
    }"
  >
    <NuxtLink to="/" :style="{ color: '#888', fontSize: '0.85rem' }">← Back to index</NuxtLink>
    <h1 :style="{ color: '#fff', margin: '0.5rem 0 0.25rem' }">Multi-Param Route — Both Params Decoded (DANGEROUS)</h1>
    <p :style="{ color: '#888', marginBottom: '1.5rem' }">
      Source: <code>useRoute().params.category</code> + <code>useRoute().params.productId</code>.
      Both are decoded by Vue Router. Concatenated URL construction means either param can traverse.
      Try:
      <NuxtLink to="/shop/..%2F..%2Fadmin/99" :style="{ color: '#f44' }">
        /shop/..%2F..%2Fadmin/99
      </NuxtLink>
    </p>

    <!-- SOURCE box -->
    <div
      :style="{
        background: '#1a1a1a',
        border: '1px solid #333',
        borderRadius: '6px',
        padding: '1rem',
        marginBottom: '1rem',
      }"
    >
      <div :style="{ color: '#888', fontSize: '0.8rem', marginBottom: '4px' }">SOURCE</div>
      <code :style="{ color: '#f90' }">route.params.category  // DECODED</code>
      <br />
      <code :style="{ color: '#f90' }">route.params.productId  // DECODED</code>
      <br />
      <code :style="{ color: '#f90', fontSize: '0.85rem' }">
        $fetch(`/api/shop/${category}/products/${productId}`)
      </code>
    </div>

    <!-- RAW VALUE box -->
    <div
      :style="{
        background: '#1a1a1a',
        border: `1px solid ${hasDots ? '#f44' : '#555'}`,
        borderRadius: '6px',
        padding: '1rem',
        marginBottom: '1rem',
      }"
    >
      <div :style="{ color: '#888', fontSize: '0.8rem', marginBottom: '4px' }">RAW VALUES from useRoute().params</div>
      <div :style="{ marginBottom: '6px' }">
        <code :style="{ color: categoryDots ? '#f44' : '#ccc' }">
          category = {{ JSON.stringify(route.params.category) }}
          <span v-if="categoryDots" :style="{ color: '#f44' }"> [TRAVERSAL DETECTED]</span>
        </code>
      </div>
      <div>
        <code :style="{ color: productDots ? '#f44' : '#ccc' }">
          productId = {{ JSON.stringify(route.params.productId) }}
          <span v-if="productDots" :style="{ color: '#f44' }"> [TRAVERSAL DETECTED]</span>
        </code>
      </div>
      <div :style="{ color: hasDots ? '#f44' : '#888', fontSize: '0.8rem', marginTop: '8px' }">
        <template v-if="hasDots">
          DANGEROUS: One or more params decoded to contain / — traversal active via concatenated URL
        </template>
        <template v-else>
          Normal values — try /shop/..%2F..%2Fadmin/99 to test traversal via category
        </template>
      </div>
    </div>

    <!-- FETCH URL box -->
    <div
      :style="{
        background: '#1a1a1a',
        border: `1px solid ${hasDots ? '#f44' : '#555'}`,
        borderRadius: '6px',
        padding: '1rem',
        marginBottom: '1rem',
      }"
    >
      <div :style="{ color: '#888', fontSize: '0.8rem', marginBottom: '4px' }">FETCH URL CONSTRUCTED</div>
      <code :style="{ color: hasDots ? '#f44' : '#ccc', fontSize: '1rem' }">
        {{ fetchUrl }}
      </code>
      <div :style="{ color: hasDots ? '#f44' : '#888', fontSize: '0.8rem', marginTop: '6px' }">
        <template v-if="hasDots">
          DANGEROUS: Decoded traversal segments in concatenated URL — server scope exceeded
        </template>
        <template v-else>
          Normal URL — both params concatenated into shop API path
        </template>
      </div>
    </div>

    <!-- RESULT box -->
    <div
      :style="{
        background: '#1a1a1a',
        border: '1px solid #555',
        borderRadius: '6px',
        padding: '1rem',
      }"
    >
      <div :style="{ color: '#888', fontSize: '0.8rem', marginBottom: '4px' }">RESULT from $fetch via useAsyncData</div>
      <pre :style="{ margin: 0, color: '#ccc', whiteSpace: 'pre-wrap' }">{{ JSON.stringify(product, null, 2) }}</pre>
    </div>
  </div>
</template>
