// sveltekit-cspt-lab/src/routes/encoding-catchall/[...rest]/+page.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import { onMount } from 'svelte';

	let windowPathname = $state('');
	let mounted = $state(false);

	const rest = $derived($page.params.rest);
	const pathname = $derived($page.url.pathname);
	const restHasDots = $derived(rest.includes('..'));
	const pathnameEncoded = $derived(pathname.includes('%2F') || pathname.includes('%2f'));
	const restDecoded = $derived(rest.includes('/') && pathnameEncoded);
	const hypotheticalFetch = $derived(`/api/files/${rest}`);

	onMount(() => {
		mounted = true;
		windowPathname = window.location.pathname;
		console.log('[ENCODING_CATCHALL] $page.params.rest:', $page.params.rest);
		console.log('[ENCODING_CATCHALL] $page.url.pathname:', $page.url.pathname);
		console.log('[ENCODING_CATCHALL] window.location.pathname:', window.location.pathname);
		console.log('[ENCODING_CATCHALL] typeof $page.params.rest:', typeof $page.params.rest);
	});
</script>

<div style="padding: 2rem; font-family: monospace; max-width: 700px; background: #111; min-height: 100vh; color: #ccc;">
  <h1 style="color: #fff;">Catch-All [...rest] Encoding</h1>
  <p style="color: #888;">
    Source: <code>$page.params.rest</code> reading <code>[...rest]</code>.
    Catch-all params in SvelteKit decode %2F — the entire rest value is decoded.
    Visit with <code>/encoding-catchall/a%2Fb/c</code> to observe.
  </p>

  <!-- SOURCE box -->
  <div style="background: #1a1a1a; border: 1px solid #333; border-radius: 6px; padding: 1rem; margin-bottom: 1rem;">
    <div style="color: #888; font-size: 0.8rem; margin-bottom: 4px;">SOURCE</div>
    <code style="color: #f90;">$page.params.rest  // [...rest] catch-all</code><br />
    <code style="color: #f90; font-size: 0.85rem;">$page.url.pathname  // encoded alternative</code>
  </div>

  <!-- RAW VALUE box -->
  <div style="background: #1a1a1a; border: 1px solid {restDecoded || restHasDots ? '#f44' : '#555'}; border-radius: 6px; padding: 1rem; margin-bottom: 1rem;">
    <div style="color: #888; font-size: 0.8rem; margin-bottom: 8px;">RAW VALUES COMPARISON</div>

    <div style="margin-bottom: 8px; padding: 8px; background: #0a0a0a; border-radius: 4px; border-left: 3px solid {restDecoded || restHasDots ? '#f44' : '#555'};">
      <div style="color: #888; font-size: 0.75rem;">$page.params.rest (type: {typeof rest})</div>
      <code style="color: {restDecoded || restHasDots ? '#f44' : '#ccc'};">{rest}</code>
      {#if restDecoded}
      <span style="color: #f44; font-size: 0.75rem; margin-left: 8px;">DECODED — %2F became /</span>
      {:else if restHasDots}
      <span style="color: #f44; font-size: 0.75rem; margin-left: 8px;">DANGEROUS — traversal dots present</span>
      {/if}
    </div>

    <div style="margin-bottom: 8px; padding: 8px; background: #0a0a0a; border-radius: 4px; border-left: 3px solid {pathnameEncoded ? '#4a4' : '#555'};">
      <div style="color: #888; font-size: 0.75rem;">$page.url.pathname</div>
      <code style="color: {pathnameEncoded ? '#4a4' : '#ccc'};">{pathname}</code>
      {#if pathnameEncoded}
      <span style="color: #4a4; font-size: 0.75rem; margin-left: 8px;">SAFE — %2F preserved</span>
      {/if}
    </div>

    {#if mounted}
    <div style="padding: 8px; background: #0a0a0a; border-radius: 4px; border-left: 3px solid #555;">
      <div style="color: #888; font-size: 0.75rem;">window.location.pathname</div>
      <code style="color: #ccc;">{windowPathname}</code>
    </div>
    {/if}

    <div style="color: {restDecoded || restHasDots ? '#f44' : '#888'}; font-size: 0.8rem; margin-top: 8px;">
      {#if restDecoded || restHasDots}
        DANGEROUS: catch-all params decode %2F — if used in fetch(), CSPT/SSRF possible
      {:else if pathnameEncoded}
        Encoded slashes only in pathname — $page.params.rest may not show differential yet
      {:else}
        Visit /encoding-catchall/a%2Fb/c to see the decoding behavior
      {/if}
    </div>
  </div>

  <!-- FETCH URL box (what would happen if used in fetch) -->
  <div style="background: #1a1a1a; border: 1px solid {restHasDots ? '#f44' : '#555'}; border-radius: 6px; padding: 1rem; margin-bottom: 1rem;">
    <div style="color: #888; font-size: 0.8rem; margin-bottom: 4px;">FETCH URL IF params.rest WERE USED</div>
    <code style="color: {restHasDots ? '#f44' : '#888'}; font-size: 0.9rem;">{hypotheticalFetch}</code>
    <div style="color: #888; font-size: 0.75rem; margin-top: 6px;">
      (hypothetical — this page does not make an actual fetch)
    </div>
    {#if restHasDots}
    <div style="color: #f44; font-size: 0.8rem; margin-top: 4px;">
      DANGEROUS: Traversal segments in hypothetical fetch URL — catch-all CSPT confirmed
    </div>
    {/if}
  </div>

  <!-- Full source table -->
  <div style="background: #1a1a1a; border: 1px solid #555; border-radius: 6px; padding: 1rem;">
    <div style="color: #888; font-size: 0.8rem; margin-bottom: 8px;">ALL SOURCES</div>
    <table style="width: 100%; border-collapse: collapse;">
      <thead>
        <tr>
          <th style="text-align: left; color: #888; font-weight: normal; font-size: 0.75rem; padding-bottom: 4px; border-bottom: 1px solid #333;">Source</th>
          <th style="text-align: left; color: #888; font-weight: normal; font-size: 0.75rem; padding-bottom: 4px; border-bottom: 1px solid #333;">Value</th>
          <th style="text-align: left; color: #888; font-weight: normal; font-size: 0.75rem; padding-bottom: 4px; border-bottom: 1px solid #333;">Safe?</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td style="padding: 4px 0; font-size: 0.85rem;">$page.params.rest</td>
          <td style="padding: 4px 4px;"><code style="color: {restDecoded || restHasDots ? '#f44' : '#ccc'};">{rest}</code></td>
          <td style="padding: 4px 0; color: {restDecoded || restHasDots ? '#f44' : '#888'};">{restDecoded || restHasDots ? 'DANGEROUS' : 'unknown'}</td>
        </tr>
        <tr>
          <td style="padding: 4px 0; font-size: 0.85rem;">$page.url.pathname</td>
          <td style="padding: 4px 4px;"><code style="color: {pathnameEncoded ? '#4a4' : '#ccc'};">{pathname}</code></td>
          <td style="padding: 4px 0; color: {pathnameEncoded ? '#4a4' : '#888'};">{pathnameEncoded ? 'SAFE' : 'n/a'}</td>
        </tr>
        {#if mounted}
        <tr>
          <td style="padding: 4px 0; font-size: 0.85rem;">window.location.pathname</td>
          <td style="padding: 4px 4px;"><code>{windowPathname}</code></td>
          <td style="padding: 4px 0; color: #888;">-</td>
        </tr>
        {/if}
      </tbody>
    </table>
  </div>

  <div style="margin-top: 1.5rem; padding: 0.75rem; background: #0a0a1a; border: 1px solid #336; border-radius: 6px;">
    <div style="color: #888; font-size: 0.75rem; margin-bottom: 4px;">TEST PAYLOADS</div>
    <a href="/encoding-catchall/..%2F..%2Fetc%2Fpasswd" style="color: #f44; display: block;">/encoding-catchall/..%2F..%2Fetc%2Fpasswd (traversal)</a>
    <a href="/encoding-catchall/a%2Fb/c" style="color: #f90; display: block;">/encoding-catchall/a%2Fb/c (encoded slash in segment)</a>
    <a href="/encoding-catchall/a/b/c" style="color: #4a4; display: block;">/encoding-catchall/a/b/c (normal)</a>
  </div>
</div>

// solidstart-cspt-lab/src/routes/encoding-catchall/[...rest].tsx
import { useParams, useLocation } from "@solidjs/router";
import { createSignal, onMount } from "solid-js";

// ENCODING COMPARISON: Catch-all param [...rest]
// Key question: Is params.rest a string or array? How are slashes handled?
// Finding: params.rest is a STRING in SolidStart (not array like Next.js)
// Encoding is preserved — %2F stays %2F even in catch-all
export default function EncodingCatchall() {
  const params = useParams<{ rest: string }>();
  const location = useLocation();
  const [windowPath, setWindowPath] = createSignal("");

  onMount(() => {
    setWindowPath(window.location.pathname);

    console.log("[ENCODING_CATCHALL] === Catch-all Encoding ===");
    console.log("[ENCODING_CATCHALL] params.rest:", params.rest);
    console.log("[ENCODING_CATCHALL] typeof params.rest:", typeof params.rest);
    console.log("[ENCODING_CATCHALL] Array.isArray(params.rest):", Array.isArray(params.rest));
    console.log("[ENCODING_CATCHALL] useLocation().pathname:", location.pathname);
    console.log("[ENCODING_CATCHALL] window.location.pathname:", window.location.pathname);
    console.log("[ENCODING_CATCHALL] Constructed fetch URL:", `/api/files/${params.rest}`);
    console.log("[ENCODING_CATCHALL] === End ===");
  });

  const isEncoded = () =>
    params.rest?.includes("%2F") || params.rest?.includes("%2f");
  const isString = () => typeof params.rest === "string";

  return (
    <div style={{ padding: "2rem", "font-family": "monospace", "max-width": "800px" }}>
      <h1>Encoding — Catch-All Param [...rest]</h1>
      <p style={{ color: "#888" }}>
        Navigate to <code>/encoding-catchall/a%2Fb/c</code> to test catch-all
        encoding. In SolidStart, <code>params.rest</code> is a{" "}
        <strong>string</strong> (unlike Next.js where catch-all params are
        arrays).
      </p>

      {/* Key finding callout */}
      <div
        style={{
          background: "#111",
          border: "1px solid #f90",
          "border-radius": "6px",
          padding: "1rem",
          "margin-bottom": "1.5rem",
        }}
      >
        <div style={{ color: "#f90", "font-size": "0.8rem", "margin-bottom": "4px" }}>
          KEY FINDINGS — CATCH-ALL
        </div>
        <div style={{ color: "#4a4" }}>
          params.rest is a STRING (not array) — SolidStart joins segments with /
        </div>
        <div style={{ color: "#4a4" }}>
          %2F is preserved in catch-all params (same as single params)
        </div>
        <div style={{ color: "#888" }}>
          /a%2Fb/c → params.rest = "a%2Fb/c" (literal slash separates real segments)
        </div>
      </div>

      {/* SOURCE box */}
      <div
        style={{
          background: "#1a1a1a",
          border: "1px solid #333",
          "border-radius": "6px",
          padding: "1rem",
          "margin-bottom": "1rem",
        }}
      >
        <div style={{ color: "#888", "font-size": "0.8rem", "margin-bottom": "4px" }}>
          SOURCE
        </div>
        <code style={{ color: "#f90" }}>
          {"const params = useParams<{ rest: string }>()"}
        </code>
        <br />
        <code style={{ color: "#f90", "font-size": "0.85rem" }}>
          {"`/api/files/${params.rest}`  →  fetch()"}
        </code>
      </div>

      {/* RAW VALUE box */}
      <div
        style={{
          background: "#1a1a1a",
          border: `1px solid ${isEncoded() ? "#4a4" : "#555"}`,
          "border-radius": "6px",
          padding: "1rem",
          "margin-bottom": "1rem",
        }}
      >
        <div style={{ color: "#888", "font-size": "0.8rem", "margin-bottom": "4px" }}>
          RAW VALUE from useParams()
        </div>
        <code style={{ color: isEncoded() ? "#4a4" : "#ccc", "font-size": "1.1rem" }}>
          rest = {JSON.stringify(params.rest)}
        </code>
        <div style={{ color: "#888", "font-size": "0.8rem", "margin-top": "4px" }}>
          typeof: <span style={{ color: isString() ? "#4a4" : "#f44" }}>{typeof params.rest}</span>
          {" "}| isArray: <span style={{ color: "#888" }}>{String(Array.isArray(params.rest))}</span>
        </div>
        <div
          style={{
            color: isEncoded() ? "#4a4" : "#888",
            "font-size": "0.8rem",
            "margin-top": "6px",
          }}
        >
          {isEncoded()
            ? "SAFE: %2F preserved in catch-all — consistent with single param behavior"
            : "No %2F present — try /encoding-catchall/a%2Fb/c"}
        </div>
      </div>

      {/* FETCH URL box */}
      <div
        style={{
          background: "#1a1a1a",
          border: "1px solid #4a4",
          "border-radius": "6px",
          padding: "1rem",
          "margin-bottom": "1rem",
        }}
      >
        <div style={{ color: "#888", "font-size": "0.8rem", "margin-bottom": "4px" }}>
          FETCH URL CONSTRUCTED
        </div>
        <code style={{ color: "#4a4", "font-size": "1rem" }}>
          {`/api/files/${params.rest}`}
        </code>
        <div style={{ color: "#4a4", "font-size": "0.8rem", "margin-top": "6px" }}>
          Catch-all value preserves encoding — %2F cannot traverse
        </div>
      </div>

      {/* Additional sources box */}
      <div
        style={{
          background: "#1a1a1a",
          border: "1px solid #333",
          "border-radius": "6px",
          padding: "1rem",
        }}
      >
        <div style={{ color: "#888", "font-size": "0.8rem", "margin-bottom": "8px" }}>
          OTHER SOURCES (for comparison)
        </div>
        <div style={{ "margin-bottom": "6px" }}>
          <span style={{ color: "#555", "font-size": "0.8rem" }}>useLocation().pathname: </span>
          <code style={{ color: "#ccc" }}>{location.pathname}</code>
        </div>
        <div>
          <span style={{ color: "#555", "font-size": "0.8rem" }}>window.location.pathname: </span>
          <code style={{ color: "#ccc" }}>{windowPath()}</code>
        </div>
      </div>
    </div>
  );
}
