// solidstart-cspt-lab/src/routes/files/[...path].tsx
import { useParams } from "@solidjs/router";
import { createResource, Show } from "solid-js";

// CSPT Pattern: useParams().path (catch-all) → fetch template literal
// Risk: LOW — SolidStart does NOT decode catch-all params either
// params.path is a string, %2F stays %2F even in [...path]
export default function FilePage() {
  const params = useParams<{ path: string }>();

  const [file] = createResource(
    () => params.path,
    async (path) => {
      const url = `/api/files/${path}`;
      console.log("[CSPT] catch-all fetch URL:", url);
      const res = await fetch(url);
      return res.json();
    }
  );

  const isEncoded = () =>
    params.path?.includes("%2F") || params.path?.includes("%2f");

  const fetchUrl = () => `/api/files/${params.path}`;

  return (
    <div style={{ padding: "2rem", "font-family": "monospace", "max-width": "700px" }}>
      <h1>useParams() — Catch-All Param [...path]</h1>
      <p style={{ color: "#888" }}>
        Source: <code>useParams().path</code> reading <code>[...path]</code>.
        Catch-all params also preserve encoding in SolidStart — %2F stays %2F.
        This is the same behavior as single params, confirming the framework-wide pattern.
      </p>

      {/* SOURCE box */}
      <div
        style={{
          background: "#1a1a1a",
          border: "1px solid #333",
          "border-radius": "6px",
          padding: "1rem",
          "margin-bottom": "1rem",
        }}
      >
        <div style={{ color: "#888", "font-size": "0.8rem", "margin-bottom": "4px" }}>
          SOURCE
        </div>
        <code style={{ color: "#f90" }}>
          {"const params = useParams<{ path: string }>()"}
        </code>
        <br />
        <code style={{ color: "#f90", "font-size": "0.85rem" }}>
          {"`/api/files/${params.path}`  →  fetch()"}
        </code>
        <div style={{ color: "#888", "font-size": "0.8rem", "margin-top": "6px" }}>
          Note: params.path is a string (not array) in SolidStart catch-all routes
        </div>
      </div>

      {/* RAW VALUE box */}
      <div
        style={{
          background: "#1a1a1a",
          border: `1px solid ${isEncoded() ? "#4a4" : "#555"}`,
          "border-radius": "6px",
          padding: "1rem",
          "margin-bottom": "1rem",
        }}
      >
        <div style={{ color: "#888", "font-size": "0.8rem", "margin-bottom": "4px" }}>
          RAW VALUE from useParams()
        </div>
        <code style={{ color: isEncoded() ? "#4a4" : "#ccc", "font-size": "1.1rem" }}>
          path = {JSON.stringify(params.path)}
        </code>
        <div style={{ color: "#888", "font-size": "0.8rem", "margin-top": "4px" }}>
          typeof: {typeof params.path}
        </div>
        <div
          style={{
            color: isEncoded() ? "#4a4" : "#888",
            "font-size": "0.8rem",
            "margin-top": "6px",
          }}
        >
          {isEncoded()
            ? "SAFE: %2F is still encoded — catch-all also preserves encoding in SolidStart"
            : "No %2F present — try /files/thepath%2fbooya to test encoding"}
        </div>
      </div>

      {/* FETCH URL box */}
      <div
        style={{
          background: "#1a1a1a",
          border: "1px solid #4a4",
          "border-radius": "6px",
          padding: "1rem",
          "margin-bottom": "1rem",
        }}
      >
        <div style={{ color: "#888", "font-size": "0.8rem", "margin-bottom": "4px" }}>
          FETCH URL CONSTRUCTED
        </div>
        <code style={{ color: "#4a4", "font-size": "1rem" }}>
          {fetchUrl()}
        </code>
        <div style={{ color: "#4a4", "font-size": "0.8rem", "margin-top": "6px" }}>
          %2F preserved — server cannot resolve ../ traversal from encoded slashes
        </div>
      </div>

      {/* RESULT box */}
      <div
        style={{
          background: "#1a1a1a",
          border: "1px solid #555",
          "border-radius": "6px",
          padding: "1rem",
        }}
      >
        <div style={{ color: "#888", "font-size": "0.8rem", "margin-bottom": "4px" }}>
          RESULT from fetch
        </div>
        <Show when={!file.loading} fallback={<span style={{ color: "#555" }}>loading...</span>}>
          <pre style={{ margin: 0, color: "#ccc" }}>
            {JSON.stringify(file(), null, 2)}
          </pre>
        </Show>
      </div>
    </div>
  );
}

// nextjs-cspt-lab/app/files/[...path]/page.tsx
// SERVER COMPONENT — catch-all route
// CSPT Pattern: await params (catch-all) → server-side fetch
// CORRECTED: Page server components get RE-ENCODED params (not decoded!)
// URL: /files/thepath%2fbooya → params.path = ["thepath%2Fbooya"] (re-encoded)
// SSRF works via indirection: page fetch → API route handler decodes → traversal

export default async function FilesPage({
  params,
}: {
  params: Promise<{ path: string[] }>;
}) {
  const { path } = await params;
  const filePath = path.join("/");
  const fetchUrl = `http://localhost:3000/api/files/${filePath}`;

  const res = await fetch(fetchUrl, { cache: "no-store" });
  const data = await res.json().catch(() => ({ error: "Failed to parse" }));

  const anyDecoded =
    filePath.includes("/") && !filePath.startsWith("/");
  const hasEncodedSlash =
    filePath.includes("%2F") || filePath.includes("%2f");

  return (
    <div style={{ padding: "2rem", fontFamily: "monospace", maxWidth: 700 }}>
      <h1>await params — Catch-All Server Component</h1>
      <p style={{ color: "#888" }}>
        Source: <code>await params</code> reading <code>[...path]</code>. Page
        server components re-encode %2F — the encoded value is then forwarded to
        the API route handler, which decodes it (indirect SSRF).
      </p>

      <div
        style={{
          background: "#1a1a1a",
          border: "1px solid #333",
          borderRadius: 6,
          padding: "1rem",
          marginBottom: "1rem",
        }}
      >
        <div style={{ color: "#888", fontSize: "0.8rem", marginBottom: 4 }}>
          SOURCE
        </div>
        <code style={{ color: "#f90" }}>
          {"const { path } = await params  // [[...path]] catch-all"}
        </code>
        <br />
        <code style={{ color: "#f90", fontSize: "0.85rem" }}>
          {"const filePath = path.join(\"/\")"}
        </code>
      </div>

      <div
        style={{
          background: "#1a1a1a",
          border: "1px solid #4a4",
          borderRadius: 6,
          padding: "1rem",
          marginBottom: "1rem",
        }}
      >
        <div style={{ color: "#888", fontSize: "0.8rem", marginBottom: 4 }}>
          RAW VALUE from await params
        </div>
        <div style={{ marginBottom: 4 }}>
          <code style={{ color: "#4a4" }}>
            params.path (array) = {JSON.stringify(path)}
          </code>
        </div>
        <div>
          <code style={{ color: "#4a4" }}>filePath = {JSON.stringify(filePath)}</code>
        </div>
        <div style={{ color: "#4a4", fontSize: "0.8rem", marginTop: 8 }}>
          {hasEncodedSlash
            ? "SAFE at this layer: %2F preserved in params — re-encoded by Next.js page component"
            : "No %2F in path — normal slash came from catch-all segment splitting"}
        </div>
      </div>

      <div
        style={{
          background: "#1a1a1a",
          border: "1px solid #f90",
          borderRadius: 6,
          padding: "1rem",
          marginBottom: "1rem",
        }}
      >
        <div style={{ color: "#888", fontSize: "0.8rem", marginBottom: 4 }}>
          FETCH URL CONSTRUCTED
        </div>
        <code style={{ color: "#f90", fontSize: "1rem" }}>{fetchUrl}</code>
        <div style={{ color: "#f90", fontSize: "0.8rem", marginTop: 6 }}>
          WARNING: The encoded %2F is forwarded to /api/files/... route handler.
          The route handler WILL decode %2F to / — traversal happens there.
        </div>
      </div>

      <div
        style={{
          background: "#1a1a1a",
          border: "1px solid #555",
          borderRadius: 6,
          padding: "1rem",
        }}
      >
        <div style={{ color: "#888", fontSize: "0.8rem", marginBottom: 4 }}>
          RESULT from fetch
        </div>
        <pre style={{ margin: 0, color: "#ccc" }}>
          {JSON.stringify(data, null, 2)}
        </pre>
      </div>
    </div>
  );
}
